# Hirundo genomic divergence landscape analysis
# pixy_summarize_autosome-Zchromosome.R - summarize mean +/- standard deviation summary statistics genome-wide, on autosomes, and on the Z chromosome

### Working directory and dependencies----
library(data.table)
library(tidyverse)
library(scales)

setwd('~/Google Drive/My Drive/projects/hirundo_divergence_landscape/analysis/pixy')

### Read in data----

## Note: the 'bs' version of the files has the complete set of pairwise measures between barn swallow subspecies
fst <- read.table('./results/pixy.all.1mb.fst.txt',header=T)
fstbs <- read.table('./results/pixy.rustica.1mb.fst.txt',header=T)

dxy <- read.table('./results/pixy.all.1mb.dxy.txt',header=T)
dxybs <- read.table('./results/pixy.rustica.1mb.dxy.txt',header=T)

pi <- read.table('./results/pixy.all.1mb.pi.txt',header=T)
pibs <- read.table('./results/pixy.rustica.1mb.pi.txt',header=T)

### Parse species----

### All Fst
fst.ery.gut <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRG'))
fst.ery.rus <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRR'))
fst.ery.sav <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRS'))
fst.ery.tra <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRV'))
fst.ery.tyt <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRT'))
fst.gut.rus <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRR'))
fst.gut.sav <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRS'))
fst.gut.tra <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRV'))
fst.gut.tyt <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRT'))
fst.rus.sav <- fstbs %>% filter((pop1 == 'HRR') & (pop2 == 'HRS'))
fst.rus.tra <- fstbs %>% filter((pop1 == 'HRR') & (pop2 == 'HRV'))
fst.rus.tyt <- fstbs %>% filter((pop1 == 'HRR') & (pop2 == 'HRT'))
fst.sav.tra <- fstbs %>% filter((pop1 == 'HRS') & (pop2 == 'HRV'))
fst.sav.tyt <- fstbs %>% filter((pop1 == 'HRS') & (pop2 == 'HRT'))
fst.tra.tyt <- fstbs %>% filter((pop1 == 'HRV') & (pop2 == 'HRT'))
fst.sav.aet <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HA'))
fst.sav.ang <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HAN'))
fst.sav.nig <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HNI'))
fst.sav.smi <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HS'))
fst.sav.alb <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HAL'))
fst.sav.neo <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HN'))
fst.sav.jav <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HT'))
fst.sav.dim <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HD'))
fst.sav.atr <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HAT'))
fst.rus.aet <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HA'))
fst.rus.ang <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HAN'))
fst.rus.nig <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HNI'))
fst.rus.smi <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HS'))
fst.rus.alb <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HAL'))
fst.rus.neo <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HN'))
fst.rus.jav <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HT'))
fst.rus.dim <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HD'))
fst.rus.atr <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HAT'))
fst.tyt.aet <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HA'))
fst.tyt.ang <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HAN'))
fst.tyt.nig <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HNI'))
fst.tyt.smi <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HS'))
fst.tyt.alb <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HAL'))
fst.tyt.neo <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HN'))
fst.tyt.jav <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HT'))
fst.tyt.dim <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HD'))
fst.tyt.atr <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HAT'))
fst.aet.ang <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HAN'))
fst.aet.nig <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HNI'))
fst.aet.smi <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HS'))
fst.aet.alb <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HAL'))
fst.aet.neo <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HN'))
fst.aet.jav <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HT'))
fst.aet.dim <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HD'))
fst.aet.atr <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HAT'))
fst.ang.smi <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HS'))
fst.ang.neo <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HN'))
fst.ang.jav <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HT'))
fst.ang.dim <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HD'))
fst.nig.smi <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HS'))
fst.nig.neo <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HN'))
fst.nig.jav <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HT'))
fst.nig.dim <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HD'))
fst.smi.alb <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HAL'))
fst.smi.neo <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HN'))
fst.smi.jav <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HT'))
fst.smi.dim <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HD'))
fst.smi.atr <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HAT'))
fst.alb.neo <- fst %>% filter((pop1 == 'HAL') & (pop2 == 'HN'))
fst.alb.jav <- fst %>% filter((pop1 == 'HAL') & (pop2 == 'HT'))
fst.alb.dim <- fst %>% filter((pop1 == 'HAL') & (pop2 == 'HD'))
fst.neo.jav <- fst %>% filter((pop1 == 'HN') & (pop2 == 'HT'))
fst.neo.dim <- fst %>% filter((pop1 == 'HN') & (pop2 == 'HD'))
fst.neo.atr <- fst %>% filter((pop1 == 'HN') & (pop2 == 'HAT'))
fst.jav.dim <- fst %>% filter((pop1 == 'HT') & (pop2 == 'HD'))
fst.jav.atr <- fst %>% filter((pop1 == 'HT') & (pop2 == 'HAT'))
fst.dim.atr <- fst %>% filter((pop1 == 'HD') & (pop2 == 'HAT'))

### Autosome Fst
fst.ery.gut.a <- fst.ery.gut %>% filter(chromosome != 'NC_053488.1')
fst.ery.rus.a <- fst.ery.rus %>% filter(chromosome != 'NC_053488.1')
fst.ery.sav.a <- fst.ery.sav %>% filter(chromosome != 'NC_053488.1')
fst.ery.tra.a <- fst.ery.tra %>% filter(chromosome != 'NC_053488.1')
fst.ery.tyt.a <- fst.ery.tyt %>% filter(chromosome != 'NC_053488.1')
fst.gut.rus.a <- fst.gut.rus %>% filter(chromosome != 'NC_053488.1')
fst.gut.sav.a <- fst.gut.sav %>% filter(chromosome != 'NC_053488.1')
fst.gut.tra.a <- fst.gut.tra %>% filter(chromosome != 'NC_053488.1')
fst.gut.tyt.a <- fst.gut.tyt %>% filter(chromosome != 'NC_053488.1')
fst.rus.sav.a <- fst.rus.sav %>% filter(chromosome != 'NC_053488.1')
fst.rus.tra.a <- fst.rus.tra %>% filter(chromosome != 'NC_053488.1')
fst.rus.tyt.a <- fst.rus.tyt %>% filter(chromosome != 'NC_053488.1')
fst.sav.tra.a <- fst.sav.tra %>% filter(chromosome != 'NC_053488.1')
fst.sav.tyt.a <- fst.sav.tyt %>% filter(chromosome != 'NC_053488.1')
fst.tra.tyt.a <- fst.tra.tyt %>% filter(chromosome != 'NC_053488.1')
fst.sav.aet.a <- fst.sav.aet %>% filter(chromosome != 'NC_053488.1')
fst.sav.ang.a <- fst.sav.ang %>% filter(chromosome != 'NC_053488.1')
fst.sav.nig.a <- fst.sav.nig %>% filter(chromosome != 'NC_053488.1')
fst.sav.smi.a <- fst.sav.smi %>% filter(chromosome != 'NC_053488.1')
fst.sav.alb.a <- fst.sav.alb %>% filter(chromosome != 'NC_053488.1')
fst.sav.neo.a <- fst.sav.neo %>% filter(chromosome != 'NC_053488.1')
fst.sav.jav.a <- fst.sav.jav %>% filter(chromosome != 'NC_053488.1')
fst.sav.dim.a <- fst.sav.dim %>% filter(chromosome != 'NC_053488.1')
fst.sav.atr.a <- fst.sav.atr %>% filter(chromosome != 'NC_053488.1')
fst.rus.aet.a <- fst.rus.aet %>% filter(chromosome != 'NC_053488.1')
fst.rus.ang.a <- fst.rus.ang %>% filter(chromosome != 'NC_053488.1')
fst.rus.nig.a <- fst.rus.nig %>% filter(chromosome != 'NC_053488.1')
fst.rus.smi.a <- fst.rus.smi %>% filter(chromosome != 'NC_053488.1')
fst.rus.alb.a <- fst.rus.alb %>% filter(chromosome != 'NC_053488.1')
fst.rus.neo.a <- fst.rus.neo %>% filter(chromosome != 'NC_053488.1')
fst.rus.jav.a <- fst.rus.jav %>% filter(chromosome != 'NC_053488.1')
fst.rus.dim.a <- fst.rus.dim %>% filter(chromosome != 'NC_053488.1')
fst.rus.atr.a <- fst.rus.atr %>% filter(chromosome != 'NC_053488.1')
fst.tyt.aet.a <- fst.tyt.aet %>% filter(chromosome != 'NC_053488.1')
fst.tyt.ang.a <- fst.tyt.ang %>% filter(chromosome != 'NC_053488.1')
fst.tyt.nig.a <- fst.tyt.nig %>% filter(chromosome != 'NC_053488.1')
fst.tyt.smi.a <- fst.tyt.smi %>% filter(chromosome != 'NC_053488.1')
fst.tyt.alb.a <- fst.tyt.alb %>% filter(chromosome != 'NC_053488.1')
fst.tyt.neo.a <- fst.tyt.neo %>% filter(chromosome != 'NC_053488.1')
fst.tyt.jav.a <- fst.tyt.jav %>% filter(chromosome != 'NC_053488.1')
fst.tyt.dim.a <- fst.tyt.dim %>% filter(chromosome != 'NC_053488.1')
fst.tyt.atr.a <- fst.tyt.atr %>% filter(chromosome != 'NC_053488.1')
fst.aet.ang.a <- fst.aet.ang %>% filter(chromosome != 'NC_053488.1')
fst.aet.nig.a <- fst.aet.nig %>% filter(chromosome != 'NC_053488.1')
fst.aet.smi.a <- fst.aet.smi %>% filter(chromosome != 'NC_053488.1')
fst.aet.alb.a <- fst.aet.alb %>% filter(chromosome != 'NC_053488.1')
fst.aet.neo.a <- fst.aet.neo %>% filter(chromosome != 'NC_053488.1')
fst.aet.jav.a <- fst.aet.jav %>% filter(chromosome != 'NC_053488.1')
fst.aet.dim.a <- fst.aet.dim %>% filter(chromosome != 'NC_053488.1')
fst.aet.atr.a <- fst.aet.atr %>% filter(chromosome != 'NC_053488.1')
fst.ang.smi.a <- fst.ang.smi %>% filter(chromosome != 'NC_053488.1')
fst.ang.neo.a <- fst.ang.neo %>% filter(chromosome != 'NC_053488.1')
fst.ang.jav.a <- fst.ang.jav %>% filter(chromosome != 'NC_053488.1')
fst.ang.dim.a <- fst.ang.dim %>% filter(chromosome != 'NC_053488.1')
fst.nig.smi.a <- fst.nig.smi %>% filter(chromosome != 'NC_053488.1')
fst.nig.neo.a <- fst.nig.neo %>% filter(chromosome != 'NC_053488.1')
fst.nig.jav.a <- fst.nig.jav %>% filter(chromosome != 'NC_053488.1')
fst.nig.dim.a <- fst.nig.dim %>% filter(chromosome != 'NC_053488.1')
fst.smi.alb.a <- fst.smi.alb %>% filter(chromosome != 'NC_053488.1')
fst.smi.neo.a <- fst.smi.neo %>% filter(chromosome != 'NC_053488.1')
fst.smi.jav.a <- fst.smi.jav %>% filter(chromosome != 'NC_053488.1')
fst.smi.dim.a <- fst.smi.dim %>% filter(chromosome != 'NC_053488.1')
fst.smi.atr.a <- fst.smi.atr %>% filter(chromosome != 'NC_053488.1')
fst.alb.neo.a <- fst.alb.neo %>% filter(chromosome != 'NC_053488.1')
fst.alb.jav.a <- fst.alb.jav %>% filter(chromosome != 'NC_053488.1')
fst.alb.dim.a <- fst.alb.dim %>% filter(chromosome != 'NC_053488.1')
fst.neo.jav.a <- fst.neo.jav %>% filter(chromosome != 'NC_053488.1')
fst.neo.dim.a <- fst.neo.dim %>% filter(chromosome != 'NC_053488.1')
fst.neo.atr.a <- fst.neo.atr %>% filter(chromosome != 'NC_053488.1')
fst.jav.dim.a <- fst.jav.dim %>% filter(chromosome != 'NC_053488.1')
fst.jav.atr.a <- fst.jav.atr %>% filter(chromosome != 'NC_053488.1')
fst.dim.atr.a <- fst.dim.atr %>% filter(chromosome != 'NC_053488.1')

### Z chromosome Fst
fst.ery.gut.z <- fst.ery.gut %>% filter(chromosome == 'NC_053488.1')
fst.ery.rus.z <- fst.ery.rus %>% filter(chromosome == 'NC_053488.1')
fst.ery.sav.z <- fst.ery.sav %>% filter(chromosome == 'NC_053488.1')
fst.ery.tra.z <- fst.ery.tra %>% filter(chromosome == 'NC_053488.1')
fst.ery.tyt.z <- fst.ery.tyt %>% filter(chromosome == 'NC_053488.1')
fst.gut.rus.z <- fst.gut.rus %>% filter(chromosome == 'NC_053488.1')
fst.gut.sav.z <- fst.gut.sav %>% filter(chromosome == 'NC_053488.1')
fst.gut.tra.z <- fst.gut.tra %>% filter(chromosome == 'NC_053488.1')
fst.gut.tyt.z <- fst.gut.tyt %>% filter(chromosome == 'NC_053488.1')
fst.rus.sav.z <- fst.rus.sav %>% filter(chromosome == 'NC_053488.1')
fst.rus.tra.z <- fst.rus.tra %>% filter(chromosome == 'NC_053488.1')
fst.rus.tyt.z <- fst.rus.tyt %>% filter(chromosome == 'NC_053488.1')
fst.sav.tra.z <- fst.sav.tra %>% filter(chromosome == 'NC_053488.1')
fst.sav.tyt.z <- fst.sav.tyt %>% filter(chromosome == 'NC_053488.1')
fst.tra.tyt.z <- fst.tra.tyt %>% filter(chromosome == 'NC_053488.1')
fst.sav.aet.z <- fst.sav.aet %>% filter(chromosome == 'NC_053488.1')
fst.sav.ang.z <- fst.sav.ang %>% filter(chromosome == 'NC_053488.1')
fst.sav.nig.z <- fst.sav.nig %>% filter(chromosome == 'NC_053488.1')
fst.sav.smi.z <- fst.sav.smi %>% filter(chromosome == 'NC_053488.1')
fst.sav.alb.z <- fst.sav.alb %>% filter(chromosome == 'NC_053488.1')
fst.sav.neo.z <- fst.sav.neo %>% filter(chromosome == 'NC_053488.1')
fst.sav.jav.z <- fst.sav.jav %>% filter(chromosome == 'NC_053488.1')
fst.sav.dim.z <- fst.sav.dim %>% filter(chromosome == 'NC_053488.1')
fst.sav.atr.z <- fst.sav.atr %>% filter(chromosome == 'NC_053488.1')
fst.rus.aet.z <- fst.rus.aet %>% filter(chromosome == 'NC_053488.1')
fst.rus.ang.z <- fst.rus.ang %>% filter(chromosome == 'NC_053488.1')
fst.rus.nig.z <- fst.rus.nig %>% filter(chromosome == 'NC_053488.1')
fst.rus.smi.z <- fst.rus.smi %>% filter(chromosome == 'NC_053488.1')
fst.rus.alb.z <- fst.rus.alb %>% filter(chromosome == 'NC_053488.1')
fst.rus.neo.z <- fst.rus.neo %>% filter(chromosome == 'NC_053488.1')
fst.rus.jav.z <- fst.rus.jav %>% filter(chromosome == 'NC_053488.1')
fst.rus.dim.z <- fst.rus.dim %>% filter(chromosome == 'NC_053488.1')
fst.rus.atr.z <- fst.rus.atr %>% filter(chromosome == 'NC_053488.1')
fst.tyt.aet.z <- fst.tyt.aet %>% filter(chromosome == 'NC_053488.1')
fst.tyt.ang.z <- fst.tyt.ang %>% filter(chromosome == 'NC_053488.1')
fst.tyt.nig.z <- fst.tyt.nig %>% filter(chromosome == 'NC_053488.1')
fst.tyt.smi.z <- fst.tyt.smi %>% filter(chromosome == 'NC_053488.1')
fst.tyt.alb.z <- fst.tyt.alb %>% filter(chromosome == 'NC_053488.1')
fst.tyt.neo.z <- fst.tyt.neo %>% filter(chromosome == 'NC_053488.1')
fst.tyt.jav.z <- fst.tyt.jav %>% filter(chromosome == 'NC_053488.1')
fst.tyt.dim.z <- fst.tyt.dim %>% filter(chromosome == 'NC_053488.1')
fst.tyt.atr.z <- fst.tyt.atr %>% filter(chromosome == 'NC_053488.1')
fst.aet.ang.z <- fst.aet.ang %>% filter(chromosome == 'NC_053488.1')
fst.aet.nig.z <- fst.aet.nig %>% filter(chromosome == 'NC_053488.1')
fst.aet.smi.z <- fst.aet.smi %>% filter(chromosome == 'NC_053488.1')
fst.aet.alb.z <- fst.aet.alb %>% filter(chromosome == 'NC_053488.1')
fst.aet.neo.z <- fst.aet.neo %>% filter(chromosome == 'NC_053488.1')
fst.aet.jav.z <- fst.aet.jav %>% filter(chromosome == 'NC_053488.1')
fst.aet.dim.z <- fst.aet.dim %>% filter(chromosome == 'NC_053488.1')
fst.aet.atr.z <- fst.aet.atr %>% filter(chromosome == 'NC_053488.1')
fst.ang.smi.z <- fst.ang.smi %>% filter(chromosome == 'NC_053488.1')
fst.ang.neo.z <- fst.ang.neo %>% filter(chromosome == 'NC_053488.1')
fst.ang.jav.z <- fst.ang.jav %>% filter(chromosome == 'NC_053488.1')
fst.ang.dim.z <- fst.ang.dim %>% filter(chromosome == 'NC_053488.1')
fst.nig.smi.z <- fst.nig.smi %>% filter(chromosome == 'NC_053488.1')
fst.nig.neo.z <- fst.nig.neo %>% filter(chromosome == 'NC_053488.1')
fst.nig.jav.z <- fst.nig.jav %>% filter(chromosome == 'NC_053488.1')
fst.nig.dim.z <- fst.nig.dim %>% filter(chromosome == 'NC_053488.1')
fst.smi.alb.z <- fst.smi.alb %>% filter(chromosome == 'NC_053488.1')
fst.smi.neo.z <- fst.smi.neo %>% filter(chromosome == 'NC_053488.1')
fst.smi.jav.z <- fst.smi.jav %>% filter(chromosome == 'NC_053488.1')
fst.smi.dim.z <- fst.smi.dim %>% filter(chromosome == 'NC_053488.1')
fst.smi.atr.z <- fst.smi.atr %>% filter(chromosome == 'NC_053488.1')
fst.alb.neo.z <- fst.alb.neo %>% filter(chromosome == 'NC_053488.1')
fst.alb.jav.z <- fst.alb.jav %>% filter(chromosome == 'NC_053488.1')
fst.alb.dim.z <- fst.alb.dim %>% filter(chromosome == 'NC_053488.1')
fst.neo.jav.z <- fst.neo.jav %>% filter(chromosome == 'NC_053488.1')
fst.neo.dim.z <- fst.neo.dim %>% filter(chromosome == 'NC_053488.1')
fst.neo.atr.z <- fst.neo.atr %>% filter(chromosome == 'NC_053488.1')
fst.jav.dim.z <- fst.jav.dim %>% filter(chromosome == 'NC_053488.1')
fst.jav.atr.z <- fst.jav.atr %>% filter(chromosome == 'NC_053488.1')
fst.dim.atr.z <- fst.dim.atr %>% filter(chromosome == 'NC_053488.1')

### All dxy
dxy.ery.gut <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRG'))
dxy.ery.rus <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRR'))
dxy.ery.sav <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRS'))
dxy.ery.tra <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRV'))
dxy.ery.tyt <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRT'))
dxy.gut.rus <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRR'))
dxy.gut.sav <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRS'))
dxy.gut.tra <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRV'))
dxy.gut.tyt <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRT'))
dxy.rus.sav <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRS'))
dxy.rus.tra <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRV'))
dxy.rus.tyt <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRT'))
dxy.sav.tra <- dxybs %>% filter((pop1 == 'HRS') & (pop2 == 'HRV'))
dxy.sav.tyt <- dxybs %>% filter((pop1 == 'HRS') & (pop2 == 'HRT'))
dxy.tra.tyt <- dxybs %>% filter((pop1 == 'HRV') & (pop2 == 'HRT'))
dxy.sav.aet <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HA'))
dxy.sav.ang <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAN'))
dxy.sav.nig <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HNI'))
dxy.sav.smi <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HS'))
dxy.sav.alb <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAL'))
dxy.sav.neo <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HN'))
dxy.sav.jav <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HT'))
dxy.sav.dim <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HD'))
dxy.sav.atr <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAT'))
dxy.rus.aet <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HA'))
dxy.rus.ang <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAN'))
dxy.rus.nig <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HNI'))
dxy.rus.smi <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HS'))
dxy.rus.alb <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAL'))
dxy.rus.neo <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HN'))
dxy.rus.jav <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HT'))
dxy.rus.dim <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HD'))
dxy.rus.atr <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAT'))
dxy.tyt.aet <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HA'))
dxy.tyt.ang <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAN'))
dxy.tyt.nig <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HNI'))
dxy.tyt.smi <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HS'))
dxy.tyt.alb <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAL'))
dxy.tyt.neo <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HN'))
dxy.tyt.jav <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HT'))
dxy.tyt.dim <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HD'))
dxy.tyt.atr <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAT'))
dxy.aet.ang <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAN'))
dxy.aet.nig <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HNI'))
dxy.aet.smi <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HS'))
dxy.aet.alb <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAL'))
dxy.aet.neo <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HN'))
dxy.aet.jav <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HT'))
dxy.aet.dim <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HD'))
dxy.aet.atr <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAT'))
dxy.ang.smi <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HS'))
dxy.ang.neo <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HN'))
dxy.ang.jav <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HT'))
dxy.ang.dim <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HD'))
dxy.nig.smi <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HS'))
dxy.nig.neo <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HN'))
dxy.nig.jav <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HT'))
dxy.nig.dim <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HD'))
dxy.smi.alb <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HAL'))
dxy.smi.neo <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HN'))
dxy.smi.jav <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HT'))
dxy.smi.dim <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HD'))
dxy.smi.atr <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HAT'))
dxy.alb.neo <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HN'))
dxy.alb.jav <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HT'))
dxy.alb.dim <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HD'))
dxy.neo.jav <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HT'))
dxy.neo.dim <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HD'))
dxy.neo.atr <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HAT'))
dxy.jav.dim <- dxy %>% filter((pop1 == 'HT') & (pop2 == 'HD'))
dxy.jav.atr <- dxy %>% filter((pop1 == 'HT') & (pop2 == 'HAT'))
dxy.dim.atr <- dxy %>% filter((pop1 == 'HD') & (pop2 == 'HAT'))

### Autosome dxy
dxy.ery.gut.a <- dxy.ery.gut %>% filter(chromosome != 'NC_053488.1')
dxy.ery.rus.a <- dxy.ery.rus %>% filter(chromosome != 'NC_053488.1')
dxy.ery.sav.a <- dxy.ery.sav %>% filter(chromosome != 'NC_053488.1')
dxy.ery.tra.a <- dxy.ery.tra %>% filter(chromosome != 'NC_053488.1')
dxy.ery.tyt.a <- dxy.ery.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.gut.rus.a <- dxy.gut.rus %>% filter(chromosome != 'NC_053488.1')
dxy.gut.sav.a <- dxy.gut.sav %>% filter(chromosome != 'NC_053488.1')
dxy.gut.tra.a <- dxy.gut.tra %>% filter(chromosome != 'NC_053488.1')
dxy.gut.tyt.a <- dxy.gut.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.rus.sav.a <- dxy.rus.sav %>% filter(chromosome != 'NC_053488.1')
dxy.rus.tra.a <- dxy.rus.tra %>% filter(chromosome != 'NC_053488.1')
dxy.rus.tyt.a <- dxy.rus.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.sav.tra.a <- dxy.sav.tra %>% filter(chromosome != 'NC_053488.1')
dxy.sav.tyt.a <- dxy.sav.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.tra.tyt.a <- dxy.tra.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.sav.aet.a <- dxy.sav.aet %>% filter(chromosome != 'NC_053488.1')
dxy.sav.ang.a <- dxy.sav.ang %>% filter(chromosome != 'NC_053488.1')
dxy.sav.nig.a <- dxy.sav.nig %>% filter(chromosome != 'NC_053488.1')
dxy.sav.smi.a <- dxy.sav.smi %>% filter(chromosome != 'NC_053488.1')
dxy.sav.alb.a <- dxy.sav.alb %>% filter(chromosome != 'NC_053488.1')
dxy.sav.neo.a <- dxy.sav.neo %>% filter(chromosome != 'NC_053488.1')
dxy.sav.jav.a <- dxy.sav.jav %>% filter(chromosome != 'NC_053488.1')
dxy.sav.dim.a <- dxy.sav.dim %>% filter(chromosome != 'NC_053488.1')
dxy.sav.atr.a <- dxy.sav.atr %>% filter(chromosome != 'NC_053488.1')
dxy.rus.aet.a <- dxy.rus.aet %>% filter(chromosome != 'NC_053488.1')
dxy.rus.ang.a <- dxy.rus.ang %>% filter(chromosome != 'NC_053488.1')
dxy.rus.nig.a <- dxy.rus.nig %>% filter(chromosome != 'NC_053488.1')
dxy.rus.smi.a <- dxy.rus.smi %>% filter(chromosome != 'NC_053488.1')
dxy.rus.alb.a <- dxy.rus.alb %>% filter(chromosome != 'NC_053488.1')
dxy.rus.neo.a <- dxy.rus.neo %>% filter(chromosome != 'NC_053488.1')
dxy.rus.jav.a <- dxy.rus.jav %>% filter(chromosome != 'NC_053488.1')
dxy.rus.dim.a <- dxy.rus.dim %>% filter(chromosome != 'NC_053488.1')
dxy.rus.atr.a <- dxy.rus.atr %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.aet.a <- dxy.tyt.aet %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.ang.a <- dxy.tyt.ang %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.nig.a <- dxy.tyt.nig %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.smi.a <- dxy.tyt.smi %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.alb.a <- dxy.tyt.alb %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.neo.a <- dxy.tyt.neo %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.jav.a <- dxy.tyt.jav %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.dim.a <- dxy.tyt.dim %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.atr.a <- dxy.tyt.atr %>% filter(chromosome != 'NC_053488.1')
dxy.aet.ang.a <- dxy.aet.ang %>% filter(chromosome != 'NC_053488.1')
dxy.aet.nig.a <- dxy.aet.nig %>% filter(chromosome != 'NC_053488.1')
dxy.aet.smi.a <- dxy.aet.smi %>% filter(chromosome != 'NC_053488.1')
dxy.aet.alb.a <- dxy.aet.alb %>% filter(chromosome != 'NC_053488.1')
dxy.aet.neo.a <- dxy.aet.neo %>% filter(chromosome != 'NC_053488.1')
dxy.aet.jav.a <- dxy.aet.jav %>% filter(chromosome != 'NC_053488.1')
dxy.aet.dim.a <- dxy.aet.dim %>% filter(chromosome != 'NC_053488.1')
dxy.aet.atr.a <- dxy.aet.atr %>% filter(chromosome != 'NC_053488.1')
dxy.ang.smi.a <- dxy.ang.smi %>% filter(chromosome != 'NC_053488.1')
dxy.ang.neo.a <- dxy.ang.neo %>% filter(chromosome != 'NC_053488.1')
dxy.ang.jav.a <- dxy.ang.jav %>% filter(chromosome != 'NC_053488.1')
dxy.ang.dim.a <- dxy.ang.dim %>% filter(chromosome != 'NC_053488.1')
dxy.nig.smi.a <- dxy.nig.smi %>% filter(chromosome != 'NC_053488.1')
dxy.nig.neo.a <- dxy.nig.neo %>% filter(chromosome != 'NC_053488.1')
dxy.nig.jav.a <- dxy.nig.jav %>% filter(chromosome != 'NC_053488.1')
dxy.nig.dim.a <- dxy.nig.dim %>% filter(chromosome != 'NC_053488.1')
dxy.smi.alb.a <- dxy.smi.alb %>% filter(chromosome != 'NC_053488.1')
dxy.smi.neo.a <- dxy.smi.neo %>% filter(chromosome != 'NC_053488.1')
dxy.smi.jav.a <- dxy.smi.jav %>% filter(chromosome != 'NC_053488.1')
dxy.smi.dim.a <- dxy.smi.dim %>% filter(chromosome != 'NC_053488.1')
dxy.smi.atr.a <- dxy.smi.atr %>% filter(chromosome != 'NC_053488.1')
dxy.alb.neo.a <- dxy.alb.neo %>% filter(chromosome != 'NC_053488.1')
dxy.alb.jav.a <- dxy.alb.jav %>% filter(chromosome != 'NC_053488.1')
dxy.alb.dim.a <- dxy.alb.dim %>% filter(chromosome != 'NC_053488.1')
dxy.neo.jav.a <- dxy.neo.jav %>% filter(chromosome != 'NC_053488.1')
dxy.neo.dim.a <- dxy.neo.dim %>% filter(chromosome != 'NC_053488.1')
dxy.neo.atr.a <- dxy.neo.atr %>% filter(chromosome != 'NC_053488.1')
dxy.jav.dim.a <- dxy.jav.dim %>% filter(chromosome != 'NC_053488.1')
dxy.jav.atr.a <- dxy.jav.atr %>% filter(chromosome != 'NC_053488.1')
dxy.dim.atr.a <- dxy.dim.atr %>% filter(chromosome != 'NC_053488.1')

### Z chromosome dxy
dxy.ery.gut.z <- dxy.ery.gut %>% filter(chromosome == 'NC_053488.1')
dxy.ery.rus.z <- dxy.ery.rus %>% filter(chromosome == 'NC_053488.1')
dxy.ery.sav.z <- dxy.ery.sav %>% filter(chromosome == 'NC_053488.1')
dxy.ery.tra.z <- dxy.ery.tra %>% filter(chromosome == 'NC_053488.1')
dxy.ery.tyt.z <- dxy.ery.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.gut.rus.z <- dxy.gut.rus %>% filter(chromosome == 'NC_053488.1')
dxy.gut.sav.z <- dxy.gut.sav %>% filter(chromosome == 'NC_053488.1')
dxy.gut.tra.z <- dxy.gut.tra %>% filter(chromosome == 'NC_053488.1')
dxy.gut.tyt.z <- dxy.gut.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.rus.sav.z <- dxy.rus.sav %>% filter(chromosome == 'NC_053488.1')
dxy.rus.tra.z <- dxy.rus.tra %>% filter(chromosome == 'NC_053488.1')
dxy.rus.tyt.z <- dxy.rus.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.sav.tra.z <- dxy.sav.tra %>% filter(chromosome == 'NC_053488.1')
dxy.sav.tyt.z <- dxy.sav.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.tra.tyt.z <- dxy.tra.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.sav.aet.z <- dxy.sav.aet %>% filter(chromosome == 'NC_053488.1')
dxy.sav.ang.z <- dxy.sav.ang %>% filter(chromosome == 'NC_053488.1')
dxy.sav.nig.z <- dxy.sav.nig %>% filter(chromosome == 'NC_053488.1')
dxy.sav.smi.z <- dxy.sav.smi %>% filter(chromosome == 'NC_053488.1')
dxy.sav.alb.z <- dxy.sav.alb %>% filter(chromosome == 'NC_053488.1')
dxy.sav.neo.z <- dxy.sav.neo %>% filter(chromosome == 'NC_053488.1')
dxy.sav.jav.z <- dxy.sav.jav %>% filter(chromosome == 'NC_053488.1')
dxy.sav.dim.z <- dxy.sav.dim %>% filter(chromosome == 'NC_053488.1')
dxy.sav.atr.z <- dxy.sav.atr %>% filter(chromosome == 'NC_053488.1')
dxy.rus.aet.z <- dxy.rus.aet %>% filter(chromosome == 'NC_053488.1')
dxy.rus.ang.z <- dxy.rus.ang %>% filter(chromosome == 'NC_053488.1')
dxy.rus.nig.z <- dxy.rus.nig %>% filter(chromosome == 'NC_053488.1')
dxy.rus.smi.z <- dxy.rus.smi %>% filter(chromosome == 'NC_053488.1')
dxy.rus.alb.z <- dxy.rus.alb %>% filter(chromosome == 'NC_053488.1')
dxy.rus.neo.z <- dxy.rus.neo %>% filter(chromosome == 'NC_053488.1')
dxy.rus.jav.z <- dxy.rus.jav %>% filter(chromosome == 'NC_053488.1')
dxy.rus.dim.z <- dxy.rus.dim %>% filter(chromosome == 'NC_053488.1')
dxy.rus.atr.z <- dxy.rus.atr %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.aet.z <- dxy.tyt.aet %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.ang.z <- dxy.tyt.ang %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.nig.z <- dxy.tyt.nig %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.smi.z <- dxy.tyt.smi %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.alb.z <- dxy.tyt.alb %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.neo.z <- dxy.tyt.neo %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.jav.z <- dxy.tyt.jav %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.dim.z <- dxy.tyt.dim %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.atr.z <- dxy.tyt.atr %>% filter(chromosome == 'NC_053488.1')
dxy.aet.ang.z <- dxy.aet.ang %>% filter(chromosome == 'NC_053488.1')
dxy.aet.nig.z <- dxy.aet.nig %>% filter(chromosome == 'NC_053488.1')
dxy.aet.smi.z <- dxy.aet.smi %>% filter(chromosome == 'NC_053488.1')
dxy.aet.alb.z <- dxy.aet.alb %>% filter(chromosome == 'NC_053488.1')
dxy.aet.neo.z <- dxy.aet.neo %>% filter(chromosome == 'NC_053488.1')
dxy.aet.jav.z <- dxy.aet.jav %>% filter(chromosome == 'NC_053488.1')
dxy.aet.dim.z <- dxy.aet.dim %>% filter(chromosome == 'NC_053488.1')
dxy.aet.atr.z <- dxy.aet.atr %>% filter(chromosome == 'NC_053488.1')
dxy.ang.smi.z <- dxy.ang.smi %>% filter(chromosome == 'NC_053488.1')
dxy.ang.neo.z <- dxy.ang.neo %>% filter(chromosome == 'NC_053488.1')
dxy.ang.jav.z <- dxy.ang.jav %>% filter(chromosome == 'NC_053488.1')
dxy.ang.dim.z <- dxy.ang.dim %>% filter(chromosome == 'NC_053488.1')
dxy.nig.smi.z <- dxy.nig.smi %>% filter(chromosome == 'NC_053488.1')
dxy.nig.neo.z <- dxy.nig.neo %>% filter(chromosome == 'NC_053488.1')
dxy.nig.jav.z <- dxy.nig.jav %>% filter(chromosome == 'NC_053488.1')
dxy.nig.dim.z <- dxy.nig.dim %>% filter(chromosome == 'NC_053488.1')
dxy.smi.alb.z <- dxy.smi.alb %>% filter(chromosome == 'NC_053488.1')
dxy.smi.neo.z <- dxy.smi.neo %>% filter(chromosome == 'NC_053488.1')
dxy.smi.jav.z <- dxy.smi.jav %>% filter(chromosome == 'NC_053488.1')
dxy.smi.dim.z <- dxy.smi.dim %>% filter(chromosome == 'NC_053488.1')
dxy.smi.atr.z <- dxy.smi.atr %>% filter(chromosome == 'NC_053488.1')
dxy.alb.neo.z <- dxy.alb.neo %>% filter(chromosome == 'NC_053488.1')
dxy.alb.jav.z <- dxy.alb.jav %>% filter(chromosome == 'NC_053488.1')
dxy.alb.dim.z <- dxy.alb.dim %>% filter(chromosome == 'NC_053488.1')
dxy.neo.jav.z <- dxy.neo.jav %>% filter(chromosome == 'NC_053488.1')
dxy.neo.dim.z <- dxy.neo.dim %>% filter(chromosome == 'NC_053488.1')
dxy.neo.atr.z <- dxy.neo.atr %>% filter(chromosome == 'NC_053488.1')
dxy.jav.dim.z <- dxy.jav.dim %>% filter(chromosome == 'NC_053488.1')
dxy.jav.atr.z <- dxy.jav.atr %>% filter(chromosome == 'NC_053488.1')
dxy.dim.atr.z <- dxy.dim.atr %>% filter(chromosome == 'NC_053488.1')

## All pi
pi.ery <- pibs %>% filter(pop == 'HRE')
pi.gut <- pibs %>% filter(pop == 'HRG')
pi.rus <- pibs %>% filter(pop == 'HRR')
pi.sav <- pibs %>% filter(pop == 'HRS')
pi.tra <- pibs %>% filter(pop == 'HRV')
pi.tyt <- pibs %>% filter(pop == 'HRT')
pi.aet <- pi %>% filter(pop == 'HA')
pi.ang <- pi %>% filter(pop == 'HAN')
pi.nig <- pi %>% filter(pop == 'HNI')
pi.alb <- pi %>% filter(pop == 'HAL')
pi.smi <- pi %>% filter(pop == 'HS')
pi.neo <- pi %>% filter(pop == 'HN')
pi.jav <- pi %>% filter(pop == 'HT')
pi.dim <- pi %>% filter(pop == 'HD')
pi.atr <- pi %>% filter(pop == 'HAT')

## Autosomal pi
pi.ery.a <- pi.ery %>% filter(chromosome != 'NC_053488.1')
pi.gut.a <- pi.gut %>% filter(chromosome != 'NC_053488.1')
pi.rus.a <- pi.rus %>% filter(chromosome != 'NC_053488.1')
pi.sav.a <- pi.sav %>% filter(chromosome != 'NC_053488.1')
pi.tra.a <- pi.tra %>% filter(chromosome != 'NC_053488.1')
pi.tyt.a <- pi.tyt %>% filter(chromosome != 'NC_053488.1')
pi.aet.a <- pi.aet %>% filter(chromosome != 'NC_053488.1')
pi.ang.a <- pi.ang %>% filter(chromosome != 'NC_053488.1')
pi.nig.a <- pi.nig %>% filter(chromosome != 'NC_053488.1')
pi.alb.a <- pi.alb %>% filter(chromosome != 'NC_053488.1')
pi.smi.a <- pi.smi %>% filter(chromosome != 'NC_053488.1')
pi.neo.a <- pi.neo %>% filter(chromosome != 'NC_053488.1')
pi.jav.a <- pi.jav %>% filter(chromosome != 'NC_053488.1')
pi.dim.a <- pi.dim %>% filter(chromosome != 'NC_053488.1')
pi.atr.a <- pi.atr %>% filter(chromosome != 'NC_053488.1')

## Z chromosome pi
pi.ery.z <- pi.ery %>% filter(chromosome == 'NC_053488.1')
pi.gut.z <- pi.gut %>% filter(chromosome == 'NC_053488.1')
pi.rus.z <- pi.rus %>% filter(chromosome == 'NC_053488.1')
pi.sav.z <- pi.sav %>% filter(chromosome == 'NC_053488.1')
pi.tra.z <- pi.tra %>% filter(chromosome == 'NC_053488.1')
pi.tyt.z <- pi.tyt %>% filter(chromosome == 'NC_053488.1')
pi.aet.z <- pi.aet %>% filter(chromosome == 'NC_053488.1')
pi.ang.z <- pi.ang %>% filter(chromosome == 'NC_053488.1')
pi.nig.z <- pi.nig %>% filter(chromosome == 'NC_053488.1')
pi.alb.z <- pi.alb %>% filter(chromosome == 'NC_053488.1')
pi.smi.z <- pi.smi %>% filter(chromosome == 'NC_053488.1')
pi.neo.z <- pi.neo %>% filter(chromosome == 'NC_053488.1')
pi.jav.z <- pi.jav %>% filter(chromosome == 'NC_053488.1')
pi.dim.z <- pi.dim %>% filter(chromosome == 'NC_053488.1')
pi.atr.z <- pi.atr %>% filter(chromosome == 'NC_053488.1')

### Extract mean and SD Fst----

## Genome-wide
mean.g <- c()
mean.g <- append(mean.g,mean(fst.ery.gut$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ery.rus$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ery.sav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ery.tra$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ery.tyt$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.gut.rus$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.gut.sav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.gut.tra$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.gut.tyt$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.sav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.tra$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.tyt$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.tra$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.tyt$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tra.tyt$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.aet$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.ang$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.nig$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.smi$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.alb$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.sav.atr$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.aet$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.ang$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.nig$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.smi$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.alb$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.rus.atr$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.aet$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.ang$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.nig$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.smi$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.alb$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.tyt.atr$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.ang$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.nig$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.smi$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.alb$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.aet.atr$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ang.smi$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ang.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ang.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.ang.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.nig.smi$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.nig.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.nig.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.nig.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.smi.alb$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.smi.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.smi.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.smi.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.smi.atr$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.alb.neo$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.alb.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.alb.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.neo.jav$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.neo.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.neo.atr$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.jav.dim$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.jav.atr$avg_wc_fst))
mean.g <- append(mean.g,mean(fst.dim.atr$avg_wc_fst))

for (i in mean.g){print (i)}

sd.g <- c()
sd.g <- append(sd.g,sd(fst.ery.gut$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ery.rus$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ery.sav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ery.tra$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ery.tyt$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.gut.rus$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.gut.sav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.gut.tra$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.gut.tyt$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.sav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.tra$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.tyt$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.tra$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.tyt$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tra.tyt$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.aet$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.ang$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.nig$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.smi$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.alb$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.sav.atr$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.aet$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.ang$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.nig$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.smi$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.alb$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.rus.atr$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.aet$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.ang$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.nig$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.smi$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.alb$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.tyt.atr$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.ang$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.nig$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.smi$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.alb$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.aet.atr$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ang.smi$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ang.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ang.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.ang.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.nig.smi$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.nig.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.nig.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.nig.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.smi.alb$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.smi.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.smi.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.smi.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.smi.atr$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.alb.neo$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.alb.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.alb.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.neo.jav$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.neo.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.neo.atr$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.jav.dim$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.jav.atr$avg_wc_fst))
sd.g <- append(sd.g,sd(fst.dim.atr$avg_wc_fst))

for (i in sd.g){print (i)}

## Autosome
mean.a <- c()
mean.a <- append(mean.a,mean(fst.ery.gut.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ery.rus.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ery.sav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ery.tra.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ery.tyt.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.gut.rus.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.gut.sav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.gut.tra.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.gut.tyt.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.sav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.tra.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.tyt.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.tra.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.tyt.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tra.tyt.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.aet.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.ang.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.nig.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.smi.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.alb.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.sav.atr.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.aet.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.ang.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.nig.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.smi.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.alb.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.rus.atr.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.aet.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.ang.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.nig.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.smi.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.alb.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.tyt.atr.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.ang.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.nig.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.smi.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.alb.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.aet.atr.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ang.smi.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ang.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ang.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.ang.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.nig.smi.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.nig.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.nig.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.nig.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.smi.alb.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.smi.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.smi.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.smi.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.smi.atr.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.alb.neo.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.alb.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.alb.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.neo.jav.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.neo.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.neo.atr.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.jav.dim.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.jav.atr.a$avg_wc_fst))
mean.a <- append(mean.a,mean(fst.dim.atr.a$avg_wc_fst))

for (i in mean.a){print (i)}

sd.a <- c()
sd.a <- append(sd.a,sd(fst.ery.gut.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ery.rus.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ery.sav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ery.tra.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ery.tyt.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.gut.rus.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.gut.sav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.gut.tra.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.gut.tyt.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.sav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.tra.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.tyt.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.tra.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.tyt.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tra.tyt.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.aet.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.ang.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.nig.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.smi.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.alb.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.sav.atr.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.aet.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.ang.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.nig.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.smi.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.alb.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.rus.atr.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.aet.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.ang.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.nig.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.smi.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.alb.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.tyt.atr.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.ang.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.nig.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.smi.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.alb.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.aet.atr.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ang.smi.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ang.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ang.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.ang.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.nig.smi.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.nig.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.nig.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.nig.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.smi.alb.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.smi.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.smi.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.smi.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.smi.atr.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.alb.neo.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.alb.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.alb.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.neo.jav.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.neo.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.neo.atr.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.jav.dim.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.jav.atr.a$avg_wc_fst))
sd.a <- append(sd.a,sd(fst.dim.atr.a$avg_wc_fst))

for (i in sd.a){print (i)}

## Z chromosome
mean.z <- c()
mean.z <- append(mean.z,mean(fst.ery.gut.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ery.rus.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ery.sav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ery.tra.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ery.tyt.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.gut.rus.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.gut.sav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.gut.tra.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.gut.tyt.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.sav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.tra.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.tyt.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.tra.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.tyt.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tra.tyt.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.aet.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.ang.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.nig.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.smi.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.alb.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.sav.atr.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.aet.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.ang.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.nig.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.smi.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.alb.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.rus.atr.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.aet.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.ang.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.nig.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.smi.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.alb.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.tyt.atr.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.ang.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.nig.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.smi.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.alb.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.aet.atr.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ang.smi.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ang.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ang.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.ang.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.nig.smi.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.nig.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.nig.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.nig.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.smi.alb.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.smi.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.smi.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.smi.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.smi.atr.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.alb.neo.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.alb.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.alb.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.neo.jav.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.neo.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.neo.atr.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.jav.dim.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.jav.atr.z$avg_wc_fst))
mean.z <- append(mean.z,mean(fst.dim.atr.z$avg_wc_fst))

for (i in mean.z){print (i)}

sd.z <- c()
sd.z <- append(sd.z,sd(fst.ery.gut.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ery.rus.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ery.sav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ery.tra.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ery.tyt.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.gut.rus.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.gut.sav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.gut.tra.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.gut.tyt.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.sav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.tra.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.tyt.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.tra.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.tyt.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tra.tyt.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.aet.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.ang.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.nig.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.smi.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.alb.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.sav.atr.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.aet.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.ang.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.nig.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.smi.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.alb.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.rus.atr.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.aet.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.ang.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.nig.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.smi.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.alb.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.tyt.atr.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.ang.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.nig.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.smi.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.alb.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.aet.atr.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ang.smi.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ang.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ang.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.ang.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.nig.smi.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.nig.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.nig.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.nig.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.smi.alb.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.smi.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.smi.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.smi.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.smi.atr.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.alb.neo.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.alb.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.alb.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.neo.jav.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.neo.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.neo.atr.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.jav.dim.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.jav.atr.z$avg_wc_fst))
sd.z <- append(sd.z,sd(fst.dim.atr.z$avg_wc_fst))

for (i in sd.z){print (i)}

### Extract mean and SD dxy----

## Genome-wide
mean.g <- c()
mean.g <- append(mean.g,mean(dxy.ery.gut$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ery.rus$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ery.sav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ery.tra$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ery.tyt$avg_dxy))
mean.g <- append(mean.g,mean(dxy.gut.rus$avg_dxy))
mean.g <- append(mean.g,mean(dxy.gut.sav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.gut.tra$avg_dxy))
mean.g <- append(mean.g,mean(dxy.gut.tyt$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.sav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.tra$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.tyt$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.tra$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.tyt$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tra.tyt$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.aet$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.ang$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.nig$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.smi$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.alb$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.sav.atr$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.aet$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.ang$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.nig$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.smi$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.alb$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.rus.atr$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.aet$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.ang$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.nig$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.smi$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.alb$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.tyt.atr$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.ang$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.nig$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.smi$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.alb$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.aet.atr$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ang.smi$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ang.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ang.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.ang.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.nig.smi$avg_dxy))
mean.g <- append(mean.g,mean(dxy.nig.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.nig.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.nig.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.smi.alb$avg_dxy))
mean.g <- append(mean.g,mean(dxy.smi.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.smi.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.smi.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.smi.atr$avg_dxy))
mean.g <- append(mean.g,mean(dxy.alb.neo$avg_dxy))
mean.g <- append(mean.g,mean(dxy.alb.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.alb.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.neo.jav$avg_dxy))
mean.g <- append(mean.g,mean(dxy.neo.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.neo.atr$avg_dxy))
mean.g <- append(mean.g,mean(dxy.jav.dim$avg_dxy))
mean.g <- append(mean.g,mean(dxy.jav.atr$avg_dxy))
mean.g <- append(mean.g,mean(dxy.dim.atr$avg_dxy))

for (i in mean.g){print (i)}

sd.g <- c()
sd.g <- append(sd.g,sd(dxy.ery.gut$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ery.rus$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ery.sav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ery.tra$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ery.tyt$avg_dxy))
sd.g <- append(sd.g,sd(dxy.gut.rus$avg_dxy))
sd.g <- append(sd.g,sd(dxy.gut.sav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.gut.tra$avg_dxy))
sd.g <- append(sd.g,sd(dxy.gut.tyt$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.sav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.tra$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.tyt$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.tra$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.tyt$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tra.tyt$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.aet$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.ang$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.nig$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.smi$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.alb$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.sav.atr$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.aet$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.ang$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.nig$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.smi$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.alb$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.rus.atr$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.aet$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.ang$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.nig$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.smi$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.alb$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.tyt.atr$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.ang$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.nig$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.smi$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.alb$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.aet.atr$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ang.smi$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ang.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ang.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.ang.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.nig.smi$avg_dxy))
sd.g <- append(sd.g,sd(dxy.nig.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.nig.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.nig.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.smi.alb$avg_dxy))
sd.g <- append(sd.g,sd(dxy.smi.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.smi.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.smi.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.smi.atr$avg_dxy))
sd.g <- append(sd.g,sd(dxy.alb.neo$avg_dxy))
sd.g <- append(sd.g,sd(dxy.alb.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.alb.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.neo.jav$avg_dxy))
sd.g <- append(sd.g,sd(dxy.neo.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.neo.atr$avg_dxy))
sd.g <- append(sd.g,sd(dxy.jav.dim$avg_dxy))
sd.g <- append(sd.g,sd(dxy.jav.atr$avg_dxy))
sd.g <- append(sd.g,sd(dxy.dim.atr$avg_dxy))

for (i in sd.g){print (i)}

## Autosome
mean.a <- c()
mean.a <- append(mean.a,mean(dxy.ery.gut.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ery.rus.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ery.sav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ery.tra.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ery.tyt.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.gut.rus.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.gut.sav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.gut.tra.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.gut.tyt.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.sav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.tra.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.tyt.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.tra.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.tyt.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tra.tyt.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.aet.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.ang.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.nig.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.smi.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.alb.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.sav.atr.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.aet.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.ang.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.nig.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.smi.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.alb.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.rus.atr.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.aet.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.ang.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.nig.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.smi.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.alb.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.tyt.atr.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.ang.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.nig.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.smi.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.alb.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.aet.atr.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ang.smi.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ang.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ang.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.ang.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.nig.smi.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.nig.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.nig.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.nig.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.smi.alb.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.smi.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.smi.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.smi.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.smi.atr.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.alb.neo.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.alb.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.alb.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.neo.jav.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.neo.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.neo.atr.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.jav.dim.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.jav.atr.a$avg_dxy))
mean.a <- append(mean.a,mean(dxy.dim.atr.a$avg_dxy))

for (i in mean.a){print (i)}

sd.a <- c()
sd.a <- append(sd.a,sd(dxy.ery.gut.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ery.rus.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ery.sav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ery.tra.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ery.tyt.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.gut.rus.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.gut.sav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.gut.tra.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.gut.tyt.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.sav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.tra.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.tyt.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.tra.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.tyt.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tra.tyt.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.aet.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.ang.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.nig.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.smi.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.alb.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.sav.atr.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.aet.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.ang.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.nig.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.smi.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.alb.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.rus.atr.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.aet.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.ang.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.nig.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.smi.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.alb.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.tyt.atr.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.ang.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.nig.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.smi.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.alb.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.aet.atr.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ang.smi.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ang.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ang.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.ang.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.nig.smi.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.nig.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.nig.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.nig.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.smi.alb.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.smi.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.smi.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.smi.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.smi.atr.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.alb.neo.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.alb.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.alb.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.neo.jav.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.neo.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.neo.atr.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.jav.dim.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.jav.atr.a$avg_dxy))
sd.a <- append(sd.a,sd(dxy.dim.atr.a$avg_dxy))

for (i in sd.a){print (i)}

## Z chromosome
mean.z <- c()
mean.z <- append(mean.z,mean(dxy.ery.gut.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ery.rus.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ery.sav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ery.tra.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ery.tyt.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.gut.rus.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.gut.sav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.gut.tra.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.gut.tyt.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.sav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.tra.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.tyt.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.tra.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.tyt.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tra.tyt.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.aet.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.ang.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.nig.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.smi.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.alb.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.sav.atr.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.aet.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.ang.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.nig.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.smi.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.alb.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.rus.atr.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.aet.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.ang.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.nig.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.smi.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.alb.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.tyt.atr.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.ang.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.nig.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.smi.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.alb.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.aet.atr.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ang.smi.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ang.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ang.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.ang.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.nig.smi.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.nig.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.nig.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.nig.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.smi.alb.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.smi.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.smi.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.smi.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.smi.atr.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.alb.neo.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.alb.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.alb.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.neo.jav.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.neo.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.neo.atr.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.jav.dim.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.jav.atr.z$avg_dxy))
mean.z <- append(mean.z,mean(dxy.dim.atr.z$avg_dxy))

for (i in mean.z){print (i)}

sd.z <- c()
sd.z <- append(sd.z,sd(dxy.ery.gut.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ery.rus.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ery.sav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ery.tra.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ery.tyt.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.gut.rus.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.gut.sav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.gut.tra.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.gut.tyt.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.sav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.tra.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.tyt.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.tra.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.tyt.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tra.tyt.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.aet.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.ang.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.nig.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.smi.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.alb.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.sav.atr.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.aet.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.ang.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.nig.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.smi.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.alb.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.rus.atr.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.aet.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.ang.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.nig.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.smi.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.alb.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.tyt.atr.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.ang.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.nig.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.smi.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.alb.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.aet.atr.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ang.smi.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ang.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ang.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.ang.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.nig.smi.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.nig.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.nig.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.nig.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.smi.alb.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.smi.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.smi.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.smi.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.smi.atr.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.alb.neo.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.alb.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.alb.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.neo.jav.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.neo.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.neo.atr.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.jav.dim.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.jav.atr.z$avg_dxy))
sd.z <- append(sd.z,sd(dxy.dim.atr.z$avg_dxy))

for (i in sd.z){print (i)}

### Extract mean and SD pi----

## Genome-wide
mean.g <- c()
mean.g <- append(mean.g,mean(pi.ery$avg_pi))
mean.g <- append(mean.g,mean(pi.gut$avg_pi))
mean.g <- append(mean.g,mean(pi.rus$avg_pi))
mean.g <- append(mean.g,mean(pi.sav$avg_pi))
mean.g <- append(mean.g,mean(pi.tra$avg_pi))
mean.g <- append(mean.g,mean(pi.tyt$avg_pi))
mean.g <- append(mean.g,mean(pi.aet$avg_pi))
mean.g <- append(mean.g,mean(pi.ang$avg_pi))
mean.g <- append(mean.g,mean(pi.nig$avg_pi))
mean.g <- append(mean.g,mean(pi.alb$avg_pi))
mean.g <- append(mean.g,mean(pi.smi$avg_pi))
mean.g <- append(mean.g,mean(pi.neo$avg_pi))
mean.g <- append(mean.g,mean(pi.jav$avg_pi))
mean.g <- append(mean.g,mean(pi.dim$avg_pi))
mean.g <- append(mean.g,mean(pi.atr$avg_pi))

for (i in mean.g){print (i)}

sd.g <- c()
sd.g <- append(sd.g,sd(pi.ery$avg_pi))
sd.g <- append(sd.g,sd(pi.gut$avg_pi))
sd.g <- append(sd.g,sd(pi.rus$avg_pi))
sd.g <- append(sd.g,sd(pi.sav$avg_pi))
sd.g <- append(sd.g,sd(pi.tra$avg_pi))
sd.g <- append(sd.g,sd(pi.tyt$avg_pi))
sd.g <- append(sd.g,sd(pi.aet$avg_pi))
sd.g <- append(sd.g,sd(pi.ang$avg_pi))
sd.g <- append(sd.g,sd(pi.nig$avg_pi))
sd.g <- append(sd.g,sd(pi.alb$avg_pi))
sd.g <- append(sd.g,sd(pi.smi$avg_pi))
sd.g <- append(sd.g,sd(pi.neo$avg_pi))
sd.g <- append(sd.g,sd(pi.jav$avg_pi))
sd.g <- append(sd.g,sd(pi.dim$avg_pi))
sd.g <- append(sd.g,sd(pi.atr$avg_pi))

for (i in sd.g){print (i)}

## Autosome
mean.a <- c()
mean.a <- append(mean.a,mean(pi.ery.a$avg_pi))
mean.a <- append(mean.a,mean(pi.gut.a$avg_pi))
mean.a <- append(mean.a,mean(pi.rus.a$avg_pi))
mean.a <- append(mean.a,mean(pi.sav.a$avg_pi))
mean.a <- append(mean.a,mean(pi.tra.a$avg_pi))
mean.a <- append(mean.a,mean(pi.tyt.a$avg_pi))
mean.a <- append(mean.a,mean(pi.aet.a$avg_pi))
mean.a <- append(mean.a,mean(pi.ang.a$avg_pi))
mean.a <- append(mean.a,mean(pi.nig.a$avg_pi))
mean.a <- append(mean.a,mean(pi.alb.a$avg_pi))
mean.a <- append(mean.a,mean(pi.smi.a$avg_pi))
mean.a <- append(mean.a,mean(pi.neo.a$avg_pi))
mean.a <- append(mean.a,mean(pi.jav.a$avg_pi))
mean.a <- append(mean.a,mean(pi.dim.a$avg_pi))
mean.a <- append(mean.a,mean(pi.atr.a$avg_pi))

for (i in mean.a){print (i)}

sd.a <- c()
sd.a <- append(sd.a,sd(pi.ery.a$avg_pi))
sd.a <- append(sd.a,sd(pi.gut.a$avg_pi))
sd.a <- append(sd.a,sd(pi.rus.a$avg_pi))
sd.a <- append(sd.a,sd(pi.sav.a$avg_pi))
sd.a <- append(sd.a,sd(pi.tra.a$avg_pi))
sd.a <- append(sd.a,sd(pi.tyt.a$avg_pi))
sd.a <- append(sd.a,sd(pi.aet.a$avg_pi))
sd.a <- append(sd.a,sd(pi.ang.a$avg_pi))
sd.a <- append(sd.a,sd(pi.nig.a$avg_pi))
sd.a <- append(sd.a,sd(pi.alb.a$avg_pi))
sd.a <- append(sd.a,sd(pi.smi.a$avg_pi))
sd.a <- append(sd.a,sd(pi.neo.a$avg_pi))
sd.a <- append(sd.a,sd(pi.jav.a$avg_pi))
sd.a <- append(sd.a,sd(pi.dim.a$avg_pi))
sd.a <- append(sd.a,sd(pi.atr.a$avg_pi))

for (i in sd.a){print (i)}

## Z chromosome
mean.z <- c()
mean.z <- append(mean.z,mean(pi.ery.z$avg_pi))
mean.z <- append(mean.z,mean(pi.gut.z$avg_pi))
mean.z <- append(mean.z,mean(pi.rus.z$avg_pi))
mean.z <- append(mean.z,mean(pi.sav.z$avg_pi))
mean.z <- append(mean.z,mean(pi.tra.z$avg_pi))
mean.z <- append(mean.z,mean(pi.tyt.z$avg_pi))
mean.z <- append(mean.z,mean(pi.aet.z$avg_pi))
mean.z <- append(mean.z,mean(pi.ang.z$avg_pi))
mean.z <- append(mean.z,mean(pi.nig.z$avg_pi))
mean.z <- append(mean.z,mean(pi.alb.z$avg_pi))
mean.z <- append(mean.z,mean(pi.smi.z$avg_pi))
mean.z <- append(mean.z,mean(pi.neo.z$avg_pi))
mean.z <- append(mean.z,mean(pi.jav.z$avg_pi))
mean.z <- append(mean.z,mean(pi.dim.z$avg_pi))
mean.z <- append(mean.z,mean(pi.atr.z$avg_pi))

for (i in mean.z){print (i)}

sd.z <- c()
sd.z <- append(sd.z,sd(pi.ery.z$avg_pi))
sd.z <- append(sd.z,sd(pi.gut.z$avg_pi))
sd.z <- append(sd.z,sd(pi.rus.z$avg_pi))
sd.z <- append(sd.z,sd(pi.sav.z$avg_pi))
sd.z <- append(sd.z,sd(pi.tra.z$avg_pi))
sd.z <- append(sd.z,sd(pi.tyt.z$avg_pi))
sd.z <- append(sd.z,sd(pi.aet.z$avg_pi))
sd.z <- append(sd.z,sd(pi.ang.z$avg_pi))
sd.z <- append(sd.z,sd(pi.nig.z$avg_pi))
sd.z <- append(sd.z,sd(pi.alb.z$avg_pi))
sd.z <- append(sd.z,sd(pi.smi.z$avg_pi))
sd.z <- append(sd.z,sd(pi.neo.z$avg_pi))
sd.z <- append(sd.z,sd(pi.jav.z$avg_pi))
sd.z <- append(sd.z,sd(pi.dim.z$avg_pi))
sd.z <- append(sd.z,sd(pi.atr.z$avg_pi))

for (i in sd.z){print (i)}