# Hirundo genomic divergence landscape analysis
# pixy_stats_divergence_correlation.R - calculate correlations between diversity and divergence landscapes

### Working directory and dependencies----
library(data.table)
library(tidyverse)
library(scales)

setwd('~/Google Drive/My Drive/projects/hirundo_divergence_landscape/analysis/pixy')

### Read in data----
dxy <- read.table('./results/pixy.all.1mb.dxy.txt',header=T)
dxybs <- read.table('./results/pixy.rustica.1mb.dxy.txt',header=T)
pi <- read.table('./results/pixy.all.1mb.pi.txt',header=T)
pibs <- read.table('./results/pixy.rustica.1mb.pi.txt',header=T)

### Parse species----

pi.ery <- pibs %>% filter(pop == 'HRE')
pi.gut <- pibs %>% filter(pop == 'HRG')
pi.rus <- pibs %>% filter(pop == 'HRR')
pi.sav <- pibs %>% filter(pop == 'HRS')
pi.tra <- pibs %>% filter(pop == 'HRV')
pi.tyt <- pibs %>% filter(pop == 'HRT')
pi.aet <- pi %>% filter(pop == 'HA')
pi.ang <- pi %>% filter(pop == 'HAN')
pi.nig <- pi %>% filter(pop == 'HNI')
pi.alb <- pi %>% filter(pop == 'HAL')
pi.smi <- pi %>% filter(pop == 'HS')
pi.neo <- pi %>% filter(pop == 'HN')
pi.jav <- pi %>% filter(pop == 'HT')
pi.dim <- pi %>% filter(pop == 'HD')
pi.atr <- pi %>% filter(pop == 'HAT')

dxy.ery.gut <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRG'))
dxy.ery.rus <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRR'))
dxy.ery.sav <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRS'))
dxy.ery.tra <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRV'))
dxy.ery.tyt <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRT'))
dxy.gut.rus <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRR'))
dxy.gut.sav <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRS'))
dxy.gut.tra <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRV'))
dxy.gut.tyt <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRT'))
dxy.rus.sav <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRS'))
dxy.rus.tra <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRV'))
dxy.rus.tyt <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRT'))
dxy.sav.tra <- dxybs %>% filter((pop1 == 'HRS') & (pop2 == 'HRV'))
dxy.sav.tyt <- dxybs %>% filter((pop1 == 'HRS') & (pop2 == 'HRT'))
dxy.tra.tyt <- dxybs %>% filter((pop1 == 'HRV') & (pop2 == 'HRT'))
dxy.sav.aet <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HA'))
dxy.sav.ang <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAN'))
dxy.sav.nig <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HNI'))
dxy.sav.smi <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HS'))
dxy.sav.alb <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAL'))
dxy.sav.neo <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HN'))
dxy.sav.jav <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HT'))
dxy.sav.dim <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HD'))
dxy.sav.atr <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAT'))
dxy.rus.aet <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HA'))
dxy.rus.ang <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAN'))
dxy.rus.nig <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HNI'))
dxy.rus.smi <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HS'))
dxy.rus.alb <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAL'))
dxy.rus.neo <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HN'))
dxy.rus.jav <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HT'))
dxy.rus.dim <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HD'))
dxy.rus.atr <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAT'))
dxy.tyt.aet <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HA'))
dxy.tyt.ang <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAN'))
dxy.tyt.nig <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HNI'))
dxy.tyt.smi <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HS'))
dxy.tyt.alb <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAL'))
dxy.tyt.neo <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HN'))
dxy.tyt.jav <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HT'))
dxy.tyt.dim <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HD'))
dxy.tyt.atr <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAT'))
dxy.aet.ang <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAN'))
dxy.aet.nig <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HNI'))
dxy.aet.smi <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HS'))
dxy.aet.alb <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAL'))
dxy.aet.neo <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HN'))
dxy.aet.jav <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HT'))
dxy.aet.dim <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HD'))
dxy.aet.atr <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAT'))
dxy.ang.nig <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HNI'))
dxy.ang.smi <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HS'))
dxy.ang.alb <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HAL'))
dxy.ang.neo <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HN'))
dxy.ang.jav <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HT'))
dxy.ang.dim <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HD'))
dxy.ang.atr <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HAT'))
dxy.nig.smi <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HS'))
dxy.nig.alb <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HAL'))
dxy.nig.neo <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HN'))
dxy.nig.jav <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HT'))
dxy.nig.dim <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HD'))
dxy.nig.atr <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HAT'))
dxy.alb.smi <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HAL'))
dxy.alb.neo <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HN'))
dxy.alb.jav <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HT'))
dxy.alb.dim <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HD'))
dxy.alb.atr <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HAT'))
dxy.smi.neo <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HN'))
dxy.smi.jav <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HT'))
dxy.smi.dim <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HD'))
dxy.smi.atr <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HAT'))
dxy.neo.jav <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HT'))
dxy.neo.dim <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HD'))
dxy.neo.atr <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HAT'))
dxy.jav.dim <- dxy %>% filter((pop1 == 'HT') & (pop2 == 'HD'))
dxy.jav.atr <- dxy %>% filter((pop1 == 'HT') & (pop2 == 'HAT'))
dxy.dim.atr <- dxy %>% filter((pop1 == 'HD') & (pop2 == 'HAT'))

### Correlations: π vs π ----

## Append correlation coefficients to vector
cors.pi.pi <- c()
cors.pi.pi <- append(cors.pi.pi,cor(pi.ery$avg_pi,pi.gut$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ery$avg_pi,pi.rus$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ery$avg_pi,pi.sav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ery$avg_pi,pi.tra$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ery$avg_pi,pi.tyt$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.gut$avg_pi,pi.rus$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.gut$avg_pi,pi.sav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.gut$avg_pi,pi.tra$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.gut$avg_pi,pi.tyt$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.sav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.tra$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.tyt$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.sav$avg_pi,pi.tra$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.sav$avg_pi,pi.tyt$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.tra$avg_pi,pi.tyt$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.aet$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.ang$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.alb$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.nig$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.smi$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.neo$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.jav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.rus$avg_pi,pi.atr$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.ang$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.alb$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.nig$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.smi$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.neo$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.jav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.aet$avg_pi,pi.atr$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ang$avg_pi,pi.smi$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ang$avg_pi,pi.neo$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ang$avg_pi,pi.jav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.ang$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.alb$avg_pi,pi.smi$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.alb$avg_pi,pi.neo$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.alb$avg_pi,pi.jav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.alb$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.nig$avg_pi,pi.smi$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.nig$avg_pi,pi.neo$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.nig$avg_pi,pi.jav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.nig$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.smi$avg_pi,pi.neo$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.smi$avg_pi,pi.jav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.smi$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.smi$avg_pi,pi.atr$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.neo$avg_pi,pi.jav$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.neo$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.neo$avg_pi,pi.atr$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.jav$avg_pi,pi.dim$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.jav$avg_pi,pi.atr$avg_pi,method='spearman'))
cors.pi.pi <- append(cors.pi.pi,cor(pi.dim$avg_pi,pi.atr$avg_pi,method='spearman'))

## Print the vector
for(i in cors.pi.pi){print(i)}

plot(cors.pi.pi,ylim=c(0,1))

### Correlations: dxy vs dxy----

## Append correlation coefficients to vector
cors.dxy.dxy <- c()
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.aet.ang$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.aet.alb$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.aet.smi$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.aet.neo$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.aet.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.aet.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.nig.smi$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.nig.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.nig.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.smi.neo$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.smi.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.smi.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.neo.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.neo.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.tyt$avg_dxy,dxy.neo.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.alb.smi$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.alb.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.alb.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.smi.neo$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.smi.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.smi.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.neo.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.jav.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.jav.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.aet$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.nig$avg_dxy,dxy.smi.neo$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.nig$avg_dxy,dxy.smi.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.nig$avg_dxy,dxy.smi.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.nig$avg_dxy,dxy.neo.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.nig$avg_dxy,dxy.neo.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.nig$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.smi$avg_dxy,dxy.neo.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.smi$avg_dxy,dxy.neo.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.smi$avg_dxy,dxy.neo.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.smi$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.rus.jav$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.alb$avg_dxy,dxy.smi.neo$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.alb$avg_dxy,dxy.smi.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.alb$avg_dxy,dxy.smi.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.alb$avg_dxy,dxy.neo.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.alb$avg_dxy,dxy.neo.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.alb$avg_dxy,dxy.neo.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.alb$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.smi$avg_dxy,dxy.neo.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.smi$avg_dxy,dxy.jav.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.smi$avg_dxy,dxy.jav.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.aet.neo$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.nig.smi$avg_dxy,dxy.neo.jav$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.nig.smi$avg_dxy,dxy.neo.dim$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.nig.smi$avg_dxy,dxy.neo.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.nig.smi$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.nig.jav$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.smi.neo$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))
cors.dxy.dxy <- append(cors.dxy.dxy,cor(dxy.neo.jav$avg_dxy,dxy.dim.atr$avg_dxy,method='spearman'))

## Print the vector
for(i in cors.dxy.dxy){print(i)}

plot(cors.dxy.dxy)

### Correlations: dxy vs π ----

## Append correlation coefficients to vector
cors.dxy.pi <- c()
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.tyt$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.aet$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.nig$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.smi$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.neo$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.dim$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.rus.atr$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.alb$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.smi$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.neo$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.dim$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.aet.atr$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.smi$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.jav$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.dim$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.nig.atr$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.neo$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.dim$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.smi.atr$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.jav$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.dim$avg_dxy,pi.atr$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.jav$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.neo.atr$avg_dxy,pi.dim$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.rus$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.aet$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.ang$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.alb$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.nig$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.smi$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.neo$avg_pi,method='spearman'))
cors.dxy.pi <- append(cors.dxy.pi,cor(dxy.dim.atr$avg_dxy,pi.jav$avg_pi,method='spearman'))

## Write the vector
for(i in cors.dxy.pi){print(i)}

plot(cors.dxy.pi,pch=20)

### Plot landscape correlations vs phylogenetic distance----

land.pi.pi <- read.table('./correlation_branch-lengths.pi-pi.txt',header=T)
land.dxy.pi <- read.table('./correlation_branch-lengths.dxy-pi.txt',header=T)
land.dxy.dxy <- read.table('./correlation_branch-lengths.dxy-dxy.txt',header=T)

par(mfrow=c(1,3))
plot(land.pi.pi$distance,land.pi.pi$correlation,pch=20,col='slategray',ylim=c(0,1),ylab='Spearman Correlation',xlab='Branch Length')
plot(land.dxy.dxy$distance,land.dxy.dxy$correlation,pch=20,col='slategray',ylim=c(0,1),ylab='Spearman Correlation',xlab='Branch Length')
plot(land.dxy.pi$distance,land.dxy.pi$correlation,pch=20,col='slategray',ylim=c(0,1),ylab='Spearman Correlation',xlab='Branch Length')
