# Hirundo genomic divergence landscape analysis
# pixy_summarizeFst.R - summarize mean genome-wide Fst between pairs of species

### Working directory and dependencies----
library(data.table)
library(tidyverse)
library(scales)

setwd('~/Google Drive/My Drive/projects/hirundo_divergence_landscape/analysis/pixy')

### Read in data----

## Note: the 'bs' version of the files has the complete set of pairwise measures between barn swallow subspecies
fst <- read.table('./results/pixy.all.1mb.fst.txt',header=T)
fstbs <- read.table('./results/pixy.rustica.1mb.fst.txt',header=T)

dxy <- read.table('./results/pixy.all.1mb.dxy.txt',header=T)
dxybs <- read.table('./results/pixy.rustica.1mb.dxy.txt',header=T)

## Parse species

### All Fst
fst.ery.gut <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRG'))
fst.ery.rus <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRR'))
fst.ery.sav <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRS'))
fst.ery.tra <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRV'))
fst.ery.tyt <- fstbs %>% filter((pop1 == 'HRE') & (pop2 == 'HRT'))
fst.gut.rus <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRR'))
fst.gut.sav <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRS'))
fst.gut.tra <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRV'))
fst.gut.tyt <- fstbs %>% filter((pop1 == 'HRG') & (pop2 == 'HRT'))
fst.rus.sav <- fstbs %>% filter((pop1 == 'HRR') & (pop2 == 'HRS'))
fst.rus.tra <- fstbs %>% filter((pop1 == 'HRR') & (pop2 == 'HRV'))
fst.rus.tyt <- fstbs %>% filter((pop1 == 'HRR') & (pop2 == 'HRT'))
fst.sav.tra <- fstbs %>% filter((pop1 == 'HRS') & (pop2 == 'HRV'))
fst.sav.tyt <- fstbs %>% filter((pop1 == 'HRS') & (pop2 == 'HRT'))
fst.tra.tyt <- fstbs %>% filter((pop1 == 'HRV') & (pop2 == 'HRT'))
fst.sav.aet <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HA'))
fst.sav.ang <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HAN'))
fst.sav.nig <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HNI'))
fst.sav.smi <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HS'))
fst.sav.alb <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HAL'))
fst.sav.neo <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HN'))
fst.sav.jav <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HT'))
fst.sav.dim <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HD'))
fst.sav.atr <- fst %>% filter((pop1 == 'HRS') & (pop2 == 'HAT'))
fst.rus.aet <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HA'))
fst.rus.ang <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HAN'))
fst.rus.nig <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HNI'))
fst.rus.smi <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HS'))
fst.rus.alb <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HAL'))
fst.rus.neo <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HN'))
fst.rus.jav <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HT'))
fst.rus.dim <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HD'))
fst.rus.atr <- fst %>% filter((pop1 == 'HRR') & (pop2 == 'HAT'))
fst.tyt.aet <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HA'))
fst.tyt.ang <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HAN'))
fst.tyt.nig <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HNI'))
fst.tyt.smi <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HS'))
fst.tyt.alb <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HAL'))
fst.tyt.neo <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HN'))
fst.tyt.jav <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HT'))
fst.tyt.dim <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HD'))
fst.tyt.atr <- fst %>% filter((pop1 == 'HRT') & (pop2 == 'HAT'))
fst.aet.ang <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HAN'))
fst.aet.nig <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HNI'))
fst.aet.smi <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HS'))
fst.aet.alb <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HAL'))
fst.aet.neo <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HN'))
fst.aet.jav <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HT'))
fst.aet.dim <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HD'))
fst.aet.atr <- fst %>% filter((pop1 == 'HA') & (pop2 == 'HAT'))
fst.ang.nig <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HNI'))
fst.ang.smi <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HS'))
fst.ang.alb <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HAL'))
fst.ang.neo <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HN'))
fst.ang.jav <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HT'))
fst.ang.dim <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HD'))
fst.ang.atr <- fst %>% filter((pop1 == 'HAN') & (pop2 == 'HAT'))
fst.nig.smi <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HS'))
fst.nig.alb <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HAL'))
fst.nig.neo <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HN'))
fst.nig.jav <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HT'))
fst.nig.dim <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HD'))
fst.nig.atr <- fst %>% filter((pop1 == 'HNI') & (pop2 == 'HAT'))
fst.smi.alb <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HAL'))
fst.smi.neo <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HN'))
fst.smi.jav <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HT'))
fst.smi.dim <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HD'))
fst.smi.atr <- fst %>% filter((pop1 == 'HS') & (pop2 == 'HAT'))
fst.alb.neo <- fst %>% filter((pop1 == 'HAL') & (pop2 == 'HN'))
fst.alb.jav <- fst %>% filter((pop1 == 'HAL') & (pop2 == 'HT'))
fst.alb.dim <- fst %>% filter((pop1 == 'HAL') & (pop2 == 'HD'))
fst.alb.atr <- fst %>% filter((pop1 == 'HAL') & (pop2 == 'HAT'))
fst.neo.jav <- fst %>% filter((pop1 == 'HN') & (pop2 == 'HT'))
fst.neo.dim <- fst %>% filter((pop1 == 'HN') & (pop2 == 'HD'))
fst.neo.atr <- fst %>% filter((pop1 == 'HN') & (pop2 == 'HAT'))
fst.jav.dim <- fst %>% filter((pop1 == 'HT') & (pop2 == 'HD'))
fst.jav.atr <- fst %>% filter((pop1 == 'HT') & (pop2 == 'HAT'))
fst.dim.atr <- fst %>% filter((pop1 == 'HD') & (pop2 == 'HAT'))

### Autosome Fst
fst.ery.gut.a <- fst.ery.gut %>% filter(chromosome != 'NC_053488.1')
fst.ery.rus.a <- fst.ery.rus %>% filter(chromosome != 'NC_053488.1')
fst.ery.sav.a <- fst.ery.sav %>% filter(chromosome != 'NC_053488.1')
fst.ery.tra.a <- fst.ery.tra %>% filter(chromosome != 'NC_053488.1')
fst.ery.tyt.a <- fst.ery.tyt %>% filter(chromosome != 'NC_053488.1')
fst.gut.rus.a <- fst.gut.rus %>% filter(chromosome != 'NC_053488.1')
fst.gut.sav.a <- fst.gut.sav %>% filter(chromosome != 'NC_053488.1')
fst.gut.tra.a <- fst.gut.tra %>% filter(chromosome != 'NC_053488.1')
fst.gut.tyt.a <- fst.gut.tyt %>% filter(chromosome != 'NC_053488.1')
fst.rus.sav.a <- fst.rus.sav %>% filter(chromosome != 'NC_053488.1')
fst.rus.tra.a <- fst.rus.tra %>% filter(chromosome != 'NC_053488.1')
fst.rus.tyt.a <- fst.rus.tyt %>% filter(chromosome != 'NC_053488.1')
fst.sav.tra.a <- fst.sav.tra %>% filter(chromosome != 'NC_053488.1')
fst.sav.tyt.a <- fst.sav.tyt %>% filter(chromosome != 'NC_053488.1')
fst.tra.tyt.a <- fst.tra.tyt %>% filter(chromosome != 'NC_053488.1')
fst.sav.aet.a <- fst.sav.aet %>% filter(chromosome != 'NC_053488.1')
fst.sav.ang.a <- fst.sav.ang %>% filter(chromosome != 'NC_053488.1')
fst.sav.nig.a <- fst.sav.nig %>% filter(chromosome != 'NC_053488.1')
fst.sav.smi.a <- fst.sav.smi %>% filter(chromosome != 'NC_053488.1')
fst.sav.alb.a <- fst.sav.alb %>% filter(chromosome != 'NC_053488.1')
fst.sav.neo.a <- fst.sav.neo %>% filter(chromosome != 'NC_053488.1')
fst.sav.jav.a <- fst.sav.jav %>% filter(chromosome != 'NC_053488.1')
fst.sav.dim.a <- fst.sav.dim %>% filter(chromosome != 'NC_053488.1')
fst.sav.atr.a <- fst.sav.atr %>% filter(chromosome != 'NC_053488.1')
fst.rus.aet.a <- fst.rus.aet %>% filter(chromosome != 'NC_053488.1')
fst.rus.ang.a <- fst.rus.ang %>% filter(chromosome != 'NC_053488.1')
fst.rus.nig.a <- fst.rus.nig %>% filter(chromosome != 'NC_053488.1')
fst.rus.smi.a <- fst.rus.smi %>% filter(chromosome != 'NC_053488.1')
fst.rus.alb.a <- fst.rus.alb %>% filter(chromosome != 'NC_053488.1')
fst.rus.neo.a <- fst.rus.neo %>% filter(chromosome != 'NC_053488.1')
fst.rus.jav.a <- fst.rus.jav %>% filter(chromosome != 'NC_053488.1')
fst.rus.dim.a <- fst.rus.dim %>% filter(chromosome != 'NC_053488.1')
fst.rus.atr.a <- fst.rus.atr %>% filter(chromosome != 'NC_053488.1')
fst.tyt.aet.a <- fst.tyt.aet %>% filter(chromosome != 'NC_053488.1')
fst.tyt.ang.a <- fst.tyt.ang %>% filter(chromosome != 'NC_053488.1')
fst.tyt.nig.a <- fst.tyt.nig %>% filter(chromosome != 'NC_053488.1')
fst.tyt.smi.a <- fst.tyt.smi %>% filter(chromosome != 'NC_053488.1')
fst.tyt.alb.a <- fst.tyt.alb %>% filter(chromosome != 'NC_053488.1')
fst.tyt.neo.a <- fst.tyt.neo %>% filter(chromosome != 'NC_053488.1')
fst.tyt.jav.a <- fst.tyt.jav %>% filter(chromosome != 'NC_053488.1')
fst.tyt.dim.a <- fst.tyt.dim %>% filter(chromosome != 'NC_053488.1')
fst.tyt.atr.a <- fst.tyt.atr %>% filter(chromosome != 'NC_053488.1')
fst.aet.ang.a <- fst.aet.ang %>% filter(chromosome != 'NC_053488.1')
fst.aet.nig.a <- fst.aet.nig %>% filter(chromosome != 'NC_053488.1')
fst.aet.smi.a <- fst.aet.smi %>% filter(chromosome != 'NC_053488.1')
fst.aet.alb.a <- fst.aet.alb %>% filter(chromosome != 'NC_053488.1')
fst.aet.neo.a <- fst.aet.neo %>% filter(chromosome != 'NC_053488.1')
fst.aet.jav.a <- fst.aet.jav %>% filter(chromosome != 'NC_053488.1')
fst.aet.dim.a <- fst.aet.dim %>% filter(chromosome != 'NC_053488.1')
fst.aet.atr.a <- fst.aet.atr %>% filter(chromosome != 'NC_053488.1')
fst.ang.nig.a <- fst.ang.nig %>% filter(chromosome != 'NC_053488.1')
fst.ang.smi.a <- fst.ang.smi %>% filter(chromosome != 'NC_053488.1')
fst.ang.alb.a <- fst.ang.alb %>% filter(chromosome != 'NC_053488.1')
fst.ang.neo.a <- fst.ang.neo %>% filter(chromosome != 'NC_053488.1')
fst.ang.jav.a <- fst.ang.jav %>% filter(chromosome != 'NC_053488.1')
fst.ang.dim.a <- fst.ang.dim %>% filter(chromosome != 'NC_053488.1')
fst.ang.atr.a <- fst.ang.atr %>% filter(chromosome != 'NC_053488.1')
fst.nig.smi.a <- fst.nig.smi %>% filter(chromosome != 'NC_053488.1')
fst.nig.alb.a <- fst.nig.alb %>% filter(chromosome != 'NC_053488.1')
fst.nig.neo.a <- fst.nig.neo %>% filter(chromosome != 'NC_053488.1')
fst.nig.jav.a <- fst.nig.jav %>% filter(chromosome != 'NC_053488.1')
fst.nig.dim.a <- fst.nig.dim %>% filter(chromosome != 'NC_053488.1')
fst.nig.atr.a <- fst.nig.atr %>% filter(chromosome != 'NC_053488.1')
fst.smi.alb.a <- fst.smi.alb %>% filter(chromosome != 'NC_053488.1')
fst.smi.neo.a <- fst.smi.neo %>% filter(chromosome != 'NC_053488.1')
fst.smi.jav.a <- fst.smi.jav %>% filter(chromosome != 'NC_053488.1')
fst.smi.dim.a <- fst.smi.dim %>% filter(chromosome != 'NC_053488.1')
fst.smi.atr.a <- fst.smi.atr %>% filter(chromosome != 'NC_053488.1')
fst.alb.neo.a <- fst.alb.neo %>% filter(chromosome != 'NC_053488.1')
fst.alb.jav.a <- fst.alb.jav %>% filter(chromosome != 'NC_053488.1')
fst.alb.dim.a <- fst.alb.dim %>% filter(chromosome != 'NC_053488.1')
fst.alb.atr.a <- fst.alb.atr %>% filter(chromosome != 'NC_053488.1')
fst.neo.jav.a <- fst.neo.jav %>% filter(chromosome != 'NC_053488.1')
fst.neo.dim.a <- fst.neo.dim %>% filter(chromosome != 'NC_053488.1')
fst.neo.atr.a <- fst.neo.atr %>% filter(chromosome != 'NC_053488.1')
fst.jav.dim.a <- fst.jav.dim %>% filter(chromosome != 'NC_053488.1')
fst.jav.atr.a <- fst.jav.atr %>% filter(chromosome != 'NC_053488.1')
fst.dim.atr.a <- fst.dim.atr %>% filter(chromosome != 'NC_053488.1')

### Z chromosome Fst
fst.ery.gut.z <- fst.ery.gut %>% filter(chromosome == 'NC_053488.1')
fst.ery.rus.z <- fst.ery.rus %>% filter(chromosome == 'NC_053488.1')
fst.ery.sav.z <- fst.ery.sav %>% filter(chromosome == 'NC_053488.1')
fst.ery.tra.z <- fst.ery.tra %>% filter(chromosome == 'NC_053488.1')
fst.ery.tyt.z <- fst.ery.tyt %>% filter(chromosome == 'NC_053488.1')
fst.gut.rus.z <- fst.gut.rus %>% filter(chromosome == 'NC_053488.1')
fst.gut.sav.z <- fst.gut.sav %>% filter(chromosome == 'NC_053488.1')
fst.gut.tra.z <- fst.gut.tra %>% filter(chromosome == 'NC_053488.1')
fst.gut.tyt.z <- fst.gut.tyt %>% filter(chromosome == 'NC_053488.1')
fst.rus.sav.z <- fst.rus.sav %>% filter(chromosome == 'NC_053488.1')
fst.rus.tra.z <- fst.rus.tra %>% filter(chromosome == 'NC_053488.1')
fst.rus.tyt.z <- fst.rus.tyt %>% filter(chromosome == 'NC_053488.1')
fst.sav.tra.z <- fst.sav.tra %>% filter(chromosome == 'NC_053488.1')
fst.sav.tyt.z <- fst.sav.tyt %>% filter(chromosome == 'NC_053488.1')
fst.tra.tyt.z <- fst.tra.tyt %>% filter(chromosome == 'NC_053488.1')
fst.sav.aet.z <- fst.sav.aet %>% filter(chromosome == 'NC_053488.1')
fst.sav.ang.z <- fst.sav.ang %>% filter(chromosome == 'NC_053488.1')
fst.sav.nig.z <- fst.sav.nig %>% filter(chromosome == 'NC_053488.1')
fst.sav.smi.z <- fst.sav.smi %>% filter(chromosome == 'NC_053488.1')
fst.sav.alb.z <- fst.sav.alb %>% filter(chromosome == 'NC_053488.1')
fst.sav.neo.z <- fst.sav.neo %>% filter(chromosome == 'NC_053488.1')
fst.sav.jav.z <- fst.sav.jav %>% filter(chromosome == 'NC_053488.1')
fst.sav.dim.z <- fst.sav.dim %>% filter(chromosome == 'NC_053488.1')
fst.sav.atr.z <- fst.sav.atr %>% filter(chromosome == 'NC_053488.1')
fst.rus.aet.z <- fst.rus.aet %>% filter(chromosome == 'NC_053488.1')
fst.rus.ang.z <- fst.rus.ang %>% filter(chromosome == 'NC_053488.1')
fst.rus.nig.z <- fst.rus.nig %>% filter(chromosome == 'NC_053488.1')
fst.rus.smi.z <- fst.rus.smi %>% filter(chromosome == 'NC_053488.1')
fst.rus.alb.z <- fst.rus.alb %>% filter(chromosome == 'NC_053488.1')
fst.rus.neo.z <- fst.rus.neo %>% filter(chromosome == 'NC_053488.1')
fst.rus.jav.z <- fst.rus.jav %>% filter(chromosome == 'NC_053488.1')
fst.rus.dim.z <- fst.rus.dim %>% filter(chromosome == 'NC_053488.1')
fst.rus.atr.z <- fst.rus.atr %>% filter(chromosome == 'NC_053488.1')
fst.tyt.aet.z <- fst.tyt.aet %>% filter(chromosome == 'NC_053488.1')
fst.tyt.ang.z <- fst.tyt.ang %>% filter(chromosome == 'NC_053488.1')
fst.tyt.nig.z <- fst.tyt.nig %>% filter(chromosome == 'NC_053488.1')
fst.tyt.smi.z <- fst.tyt.smi %>% filter(chromosome == 'NC_053488.1')
fst.tyt.alb.z <- fst.tyt.alb %>% filter(chromosome == 'NC_053488.1')
fst.tyt.neo.z <- fst.tyt.neo %>% filter(chromosome == 'NC_053488.1')
fst.tyt.jav.z <- fst.tyt.jav %>% filter(chromosome == 'NC_053488.1')
fst.tyt.dim.z <- fst.tyt.dim %>% filter(chromosome == 'NC_053488.1')
fst.tyt.atr.z <- fst.tyt.atr %>% filter(chromosome == 'NC_053488.1')
fst.aet.ang.z <- fst.aet.ang %>% filter(chromosome == 'NC_053488.1')
fst.aet.nig.z <- fst.aet.nig %>% filter(chromosome == 'NC_053488.1')
fst.aet.smi.z <- fst.aet.smi %>% filter(chromosome == 'NC_053488.1')
fst.aet.alb.z <- fst.aet.alb %>% filter(chromosome == 'NC_053488.1')
fst.aet.neo.z <- fst.aet.neo %>% filter(chromosome == 'NC_053488.1')
fst.aet.jav.z <- fst.aet.jav %>% filter(chromosome == 'NC_053488.1')
fst.aet.dim.z <- fst.aet.dim %>% filter(chromosome == 'NC_053488.1')
fst.aet.atr.z <- fst.aet.atr %>% filter(chromosome == 'NC_053488.1')
fst.ang.nig.z <- fst.ang.nig %>% filter(chromosome == 'NC_053488.1')
fst.ang.smi.z <- fst.ang.smi %>% filter(chromosome == 'NC_053488.1')
fst.ang.alb.z <- fst.ang.alb %>% filter(chromosome == 'NC_053488.1')
fst.ang.neo.z <- fst.ang.neo %>% filter(chromosome == 'NC_053488.1')
fst.ang.jav.z <- fst.ang.jav %>% filter(chromosome == 'NC_053488.1')
fst.ang.dim.z <- fst.ang.dim %>% filter(chromosome == 'NC_053488.1')
fst.ang.atr.z <- fst.ang.atr %>% filter(chromosome == 'NC_053488.1')
fst.nig.smi.z <- fst.nig.smi %>% filter(chromosome == 'NC_053488.1')
fst.nig.alb.z <- fst.nig.alb %>% filter(chromosome == 'NC_053488.1')
fst.nig.neo.z <- fst.nig.neo %>% filter(chromosome == 'NC_053488.1')
fst.nig.jav.z <- fst.nig.jav %>% filter(chromosome == 'NC_053488.1')
fst.nig.dim.z <- fst.nig.dim %>% filter(chromosome == 'NC_053488.1')
fst.nig.atr.z <- fst.nig.atr %>% filter(chromosome == 'NC_053488.1')
fst.smi.alb.z <- fst.smi.alb %>% filter(chromosome == 'NC_053488.1')
fst.smi.neo.z <- fst.smi.neo %>% filter(chromosome == 'NC_053488.1')
fst.smi.jav.z <- fst.smi.jav %>% filter(chromosome == 'NC_053488.1')
fst.smi.dim.z <- fst.smi.dim %>% filter(chromosome == 'NC_053488.1')
fst.smi.atr.z <- fst.smi.atr %>% filter(chromosome == 'NC_053488.1')
fst.alb.neo.z <- fst.alb.neo %>% filter(chromosome == 'NC_053488.1')
fst.alb.jav.z <- fst.alb.jav %>% filter(chromosome == 'NC_053488.1')
fst.alb.dim.z <- fst.alb.dim %>% filter(chromosome == 'NC_053488.1')
fst.alb.atr.z <- fst.alb.atr %>% filter(chromosome == 'NC_053488.1')
fst.neo.jav.z <- fst.neo.jav %>% filter(chromosome == 'NC_053488.1')
fst.neo.dim.z <- fst.neo.dim %>% filter(chromosome == 'NC_053488.1')
fst.neo.atr.z <- fst.neo.atr %>% filter(chromosome == 'NC_053488.1')
fst.jav.dim.z <- fst.jav.dim %>% filter(chromosome == 'NC_053488.1')
fst.jav.atr.z <- fst.jav.atr %>% filter(chromosome == 'NC_053488.1')
fst.dim.atr.z <- fst.dim.atr %>% filter(chromosome == 'NC_053488.1')

### All dxy
dxy.ery.gut <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRG'))
dxy.ery.rus <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRR'))
dxy.ery.sav <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRS'))
dxy.ery.tra <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRV'))
dxy.ery.tyt <- dxybs %>% filter((pop1 == 'HRE') & (pop2 == 'HRT'))
dxy.gut.rus <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRR'))
dxy.gut.sav <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRS'))
dxy.gut.tra <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRV'))
dxy.gut.tyt <- dxybs %>% filter((pop1 == 'HRG') & (pop2 == 'HRT'))
dxy.rus.sav <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRS'))
dxy.rus.tra <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRV'))
dxy.rus.tyt <- dxybs %>% filter((pop1 == 'HRR') & (pop2 == 'HRT'))
dxy.sav.tra <- dxybs %>% filter((pop1 == 'HRS') & (pop2 == 'HRV'))
dxy.sav.tyt <- dxybs %>% filter((pop1 == 'HRS') & (pop2 == 'HRT'))
dxy.tra.tyt <- dxybs %>% filter((pop1 == 'HRV') & (pop2 == 'HRT'))
dxy.sav.aet <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HA'))
dxy.sav.ang <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAN'))
dxy.sav.nig <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HNI'))
dxy.sav.smi <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HS'))
dxy.sav.alb <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAL'))
dxy.sav.neo <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HN'))
dxy.sav.jav <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HT'))
dxy.sav.dim <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HD'))
dxy.sav.atr <- dxy %>% filter((pop1 == 'HRS') & (pop2 == 'HAT'))
dxy.rus.aet <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HA'))
dxy.rus.ang <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAN'))
dxy.rus.nig <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HNI'))
dxy.rus.smi <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HS'))
dxy.rus.alb <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAL'))
dxy.rus.neo <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HN'))
dxy.rus.jav <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HT'))
dxy.rus.dim <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HD'))
dxy.rus.atr <- dxy %>% filter((pop1 == 'HRR') & (pop2 == 'HAT'))
dxy.tyt.aet <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HA'))
dxy.tyt.ang <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAN'))
dxy.tyt.nig <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HNI'))
dxy.tyt.smi <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HS'))
dxy.tyt.alb <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAL'))
dxy.tyt.neo <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HN'))
dxy.tyt.jav <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HT'))
dxy.tyt.dim <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HD'))
dxy.tyt.atr <- dxy %>% filter((pop1 == 'HRT') & (pop2 == 'HAT'))
dxy.aet.ang <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAN'))
dxy.aet.nig <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HNI'))
dxy.aet.smi <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HS'))
dxy.aet.alb <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAL'))
dxy.aet.neo <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HN'))
dxy.aet.jav <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HT'))
dxy.aet.dim <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HD'))
dxy.aet.atr <- dxy %>% filter((pop1 == 'HA') & (pop2 == 'HAT'))
dxy.ang.nig <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HNI'))
dxy.ang.smi <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HS'))
dxy.ang.alb <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HAL'))
dxy.ang.neo <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HN'))
dxy.ang.jav <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HT'))
dxy.ang.dim <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HD'))
dxy.ang.atr <- dxy %>% filter((pop1 == 'HAN') & (pop2 == 'HAT'))
dxy.nig.smi <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HS'))
dxy.nig.alb <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HAL'))
dxy.nig.neo <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HN'))
dxy.nig.jav <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HT'))
dxy.nig.dim <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HD'))
dxy.nig.atr <- dxy %>% filter((pop1 == 'HNI') & (pop2 == 'HAT'))
dxy.smi.alb <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HAL'))
dxy.smi.neo <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HN'))
dxy.smi.jav <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HT'))
dxy.smi.dim <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HD'))
dxy.smi.atr <- dxy %>% filter((pop1 == 'HS') & (pop2 == 'HAT'))
dxy.alb.neo <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HN'))
dxy.alb.jav <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HT'))
dxy.alb.dim <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HD'))
dxy.alb.atr <- dxy %>% filter((pop1 == 'HAL') & (pop2 == 'HAT'))
dxy.neo.jav <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HT'))
dxy.neo.dim <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HD'))
dxy.neo.atr <- dxy %>% filter((pop1 == 'HN') & (pop2 == 'HAT'))
dxy.jav.dim <- dxy %>% filter((pop1 == 'HT') & (pop2 == 'HD'))
dxy.jav.atr <- dxy %>% filter((pop1 == 'HT') & (pop2 == 'HAT'))
dxy.dim.atr <- dxy %>% filter((pop1 == 'HD') & (pop2 == 'HAT'))

### Autosome dxy
dxy.ery.gut.a <- dxy.ery.gut %>% filter(chromosome != 'NC_053488.1')
dxy.ery.rus.a <- dxy.ery.rus %>% filter(chromosome != 'NC_053488.1')
dxy.ery.sav.a <- dxy.ery.sav %>% filter(chromosome != 'NC_053488.1')
dxy.ery.tra.a <- dxy.ery.tra %>% filter(chromosome != 'NC_053488.1')
dxy.ery.tyt.a <- dxy.ery.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.gut.rus.a <- dxy.gut.rus %>% filter(chromosome != 'NC_053488.1')
dxy.gut.sav.a <- dxy.gut.sav %>% filter(chromosome != 'NC_053488.1')
dxy.gut.tra.a <- dxy.gut.tra %>% filter(chromosome != 'NC_053488.1')
dxy.gut.tyt.a <- dxy.gut.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.rus.sav.a <- dxy.rus.sav %>% filter(chromosome != 'NC_053488.1')
dxy.rus.tra.a <- dxy.rus.tra %>% filter(chromosome != 'NC_053488.1')
dxy.rus.tyt.a <- dxy.rus.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.sav.tra.a <- dxy.sav.tra %>% filter(chromosome != 'NC_053488.1')
dxy.sav.tyt.a <- dxy.sav.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.tra.tyt.a <- dxy.tra.tyt %>% filter(chromosome != 'NC_053488.1')
dxy.sav.aet.a <- dxy.sav.aet %>% filter(chromosome != 'NC_053488.1')
dxy.sav.ang.a <- dxy.sav.ang %>% filter(chromosome != 'NC_053488.1')
dxy.sav.nig.a <- dxy.sav.nig %>% filter(chromosome != 'NC_053488.1')
dxy.sav.smi.a <- dxy.sav.smi %>% filter(chromosome != 'NC_053488.1')
dxy.sav.alb.a <- dxy.sav.alb %>% filter(chromosome != 'NC_053488.1')
dxy.sav.neo.a <- dxy.sav.neo %>% filter(chromosome != 'NC_053488.1')
dxy.sav.jav.a <- dxy.sav.jav %>% filter(chromosome != 'NC_053488.1')
dxy.sav.dim.a <- dxy.sav.dim %>% filter(chromosome != 'NC_053488.1')
dxy.sav.atr.a <- dxy.sav.atr %>% filter(chromosome != 'NC_053488.1')
dxy.rus.aet.a <- dxy.rus.aet %>% filter(chromosome != 'NC_053488.1')
dxy.rus.ang.a <- dxy.rus.ang %>% filter(chromosome != 'NC_053488.1')
dxy.rus.nig.a <- dxy.rus.nig %>% filter(chromosome != 'NC_053488.1')
dxy.rus.smi.a <- dxy.rus.smi %>% filter(chromosome != 'NC_053488.1')
dxy.rus.alb.a <- dxy.rus.alb %>% filter(chromosome != 'NC_053488.1')
dxy.rus.neo.a <- dxy.rus.neo %>% filter(chromosome != 'NC_053488.1')
dxy.rus.jav.a <- dxy.rus.jav %>% filter(chromosome != 'NC_053488.1')
dxy.rus.dim.a <- dxy.rus.dim %>% filter(chromosome != 'NC_053488.1')
dxy.rus.atr.a <- dxy.rus.atr %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.aet.a <- dxy.tyt.aet %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.ang.a <- dxy.tyt.ang %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.nig.a <- dxy.tyt.nig %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.smi.a <- dxy.tyt.smi %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.alb.a <- dxy.tyt.alb %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.neo.a <- dxy.tyt.neo %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.jav.a <- dxy.tyt.jav %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.dim.a <- dxy.tyt.dim %>% filter(chromosome != 'NC_053488.1')
dxy.tyt.atr.a <- dxy.tyt.atr %>% filter(chromosome != 'NC_053488.1')
dxy.aet.ang.a <- dxy.aet.ang %>% filter(chromosome != 'NC_053488.1')
dxy.aet.nig.a <- dxy.aet.nig %>% filter(chromosome != 'NC_053488.1')
dxy.aet.smi.a <- dxy.aet.smi %>% filter(chromosome != 'NC_053488.1')
dxy.aet.alb.a <- dxy.aet.alb %>% filter(chromosome != 'NC_053488.1')
dxy.aet.neo.a <- dxy.aet.neo %>% filter(chromosome != 'NC_053488.1')
dxy.aet.jav.a <- dxy.aet.jav %>% filter(chromosome != 'NC_053488.1')
dxy.aet.dim.a <- dxy.aet.dim %>% filter(chromosome != 'NC_053488.1')
dxy.aet.atr.a <- dxy.aet.atr %>% filter(chromosome != 'NC_053488.1')
dxy.ang.nig.a <- dxy.ang.nig %>% filter(chromosome != 'NC_053488.1')
dxy.ang.smi.a <- dxy.ang.smi %>% filter(chromosome != 'NC_053488.1')
dxy.ang.alb.a <- dxy.ang.alb %>% filter(chromosome != 'NC_053488.1')
dxy.ang.neo.a <- dxy.ang.neo %>% filter(chromosome != 'NC_053488.1')
dxy.ang.jav.a <- dxy.ang.jav %>% filter(chromosome != 'NC_053488.1')
dxy.ang.dim.a <- dxy.ang.dim %>% filter(chromosome != 'NC_053488.1')
dxy.ang.atr.a <- dxy.ang.atr %>% filter(chromosome != 'NC_053488.1')
dxy.nig.smi.a <- dxy.nig.smi %>% filter(chromosome != 'NC_053488.1')
dxy.nig.alb.a <- dxy.nig.alb %>% filter(chromosome != 'NC_053488.1')
dxy.nig.neo.a <- dxy.nig.neo %>% filter(chromosome != 'NC_053488.1')
dxy.nig.jav.a <- dxy.nig.jav %>% filter(chromosome != 'NC_053488.1')
dxy.nig.dim.a <- dxy.nig.dim %>% filter(chromosome != 'NC_053488.1')
dxy.nig.atr.a <- dxy.nig.atr %>% filter(chromosome != 'NC_053488.1')
dxy.smi.alb.a <- dxy.smi.alb %>% filter(chromosome != 'NC_053488.1')
dxy.smi.neo.a <- dxy.smi.neo %>% filter(chromosome != 'NC_053488.1')
dxy.smi.jav.a <- dxy.smi.jav %>% filter(chromosome != 'NC_053488.1')
dxy.smi.dim.a <- dxy.smi.dim %>% filter(chromosome != 'NC_053488.1')
dxy.smi.atr.a <- dxy.smi.atr %>% filter(chromosome != 'NC_053488.1')
dxy.alb.neo.a <- dxy.alb.neo %>% filter(chromosome != 'NC_053488.1')
dxy.alb.jav.a <- dxy.alb.jav %>% filter(chromosome != 'NC_053488.1')
dxy.alb.dim.a <- dxy.alb.dim %>% filter(chromosome != 'NC_053488.1')
dxy.alb.atr.a <- dxy.alb.atr %>% filter(chromosome != 'NC_053488.1')
dxy.neo.jav.a <- dxy.neo.jav %>% filter(chromosome != 'NC_053488.1')
dxy.neo.dim.a <- dxy.neo.dim %>% filter(chromosome != 'NC_053488.1')
dxy.neo.atr.a <- dxy.neo.atr %>% filter(chromosome != 'NC_053488.1')
dxy.jav.dim.a <- dxy.jav.dim %>% filter(chromosome != 'NC_053488.1')
dxy.jav.atr.a <- dxy.jav.atr %>% filter(chromosome != 'NC_053488.1')
dxy.dim.atr.a <- dxy.dim.atr %>% filter(chromosome != 'NC_053488.1')

### Z chromosome dxy
dxy.ery.gut.z <- dxy.ery.gut %>% filter(chromosome == 'NC_053488.1')
dxy.ery.rus.z <- dxy.ery.rus %>% filter(chromosome == 'NC_053488.1')
dxy.ery.sav.z <- dxy.ery.sav %>% filter(chromosome == 'NC_053488.1')
dxy.ery.tra.z <- dxy.ery.tra %>% filter(chromosome == 'NC_053488.1')
dxy.ery.tyt.z <- dxy.ery.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.gut.rus.z <- dxy.gut.rus %>% filter(chromosome == 'NC_053488.1')
dxy.gut.sav.z <- dxy.gut.sav %>% filter(chromosome == 'NC_053488.1')
dxy.gut.tra.z <- dxy.gut.tra %>% filter(chromosome == 'NC_053488.1')
dxy.gut.tyt.z <- dxy.gut.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.rus.sav.z <- dxy.rus.sav %>% filter(chromosome == 'NC_053488.1')
dxy.rus.tra.z <- dxy.rus.tra %>% filter(chromosome == 'NC_053488.1')
dxy.rus.tyt.z <- dxy.rus.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.sav.tra.z <- dxy.sav.tra %>% filter(chromosome == 'NC_053488.1')
dxy.sav.tyt.z <- dxy.sav.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.tra.tyt.z <- dxy.tra.tyt %>% filter(chromosome == 'NC_053488.1')
dxy.sav.aet.z <- dxy.sav.aet %>% filter(chromosome == 'NC_053488.1')
dxy.sav.ang.z <- dxy.sav.ang %>% filter(chromosome == 'NC_053488.1')
dxy.sav.nig.z <- dxy.sav.nig %>% filter(chromosome == 'NC_053488.1')
dxy.sav.smi.z <- dxy.sav.smi %>% filter(chromosome == 'NC_053488.1')
dxy.sav.alb.z <- dxy.sav.alb %>% filter(chromosome == 'NC_053488.1')
dxy.sav.neo.z <- dxy.sav.neo %>% filter(chromosome == 'NC_053488.1')
dxy.sav.jav.z <- dxy.sav.jav %>% filter(chromosome == 'NC_053488.1')
dxy.sav.dim.z <- dxy.sav.dim %>% filter(chromosome == 'NC_053488.1')
dxy.sav.atr.z <- dxy.sav.atr %>% filter(chromosome == 'NC_053488.1')
dxy.rus.aet.z <- dxy.rus.aet %>% filter(chromosome == 'NC_053488.1')
dxy.rus.ang.z <- dxy.rus.ang %>% filter(chromosome == 'NC_053488.1')
dxy.rus.nig.z <- dxy.rus.nig %>% filter(chromosome == 'NC_053488.1')
dxy.rus.smi.z <- dxy.rus.smi %>% filter(chromosome == 'NC_053488.1')
dxy.rus.alb.z <- dxy.rus.alb %>% filter(chromosome == 'NC_053488.1')
dxy.rus.neo.z <- dxy.rus.neo %>% filter(chromosome == 'NC_053488.1')
dxy.rus.jav.z <- dxy.rus.jav %>% filter(chromosome == 'NC_053488.1')
dxy.rus.dim.z <- dxy.rus.dim %>% filter(chromosome == 'NC_053488.1')
dxy.rus.atr.z <- dxy.rus.atr %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.aet.z <- dxy.tyt.aet %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.ang.z <- dxy.tyt.ang %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.nig.z <- dxy.tyt.nig %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.smi.z <- dxy.tyt.smi %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.alb.z <- dxy.tyt.alb %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.neo.z <- dxy.tyt.neo %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.jav.z <- dxy.tyt.jav %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.dim.z <- dxy.tyt.dim %>% filter(chromosome == 'NC_053488.1')
dxy.tyt.atr.z <- dxy.tyt.atr %>% filter(chromosome == 'NC_053488.1')
dxy.aet.ang.z <- dxy.aet.ang %>% filter(chromosome == 'NC_053488.1')
dxy.aet.nig.z <- dxy.aet.nig %>% filter(chromosome == 'NC_053488.1')
dxy.aet.smi.z <- dxy.aet.smi %>% filter(chromosome == 'NC_053488.1')
dxy.aet.alb.z <- dxy.aet.alb %>% filter(chromosome == 'NC_053488.1')
dxy.aet.neo.z <- dxy.aet.neo %>% filter(chromosome == 'NC_053488.1')
dxy.aet.jav.z <- dxy.aet.jav %>% filter(chromosome == 'NC_053488.1')
dxy.aet.dim.z <- dxy.aet.dim %>% filter(chromosome == 'NC_053488.1')
dxy.aet.atr.z <- dxy.aet.atr %>% filter(chromosome == 'NC_053488.1')
dxy.ang.nig.z <- dxy.ang.nig %>% filter(chromosome == 'NC_053488.1')
dxy.ang.smi.z <- dxy.ang.smi %>% filter(chromosome == 'NC_053488.1')
dxy.ang.alb.z <- dxy.ang.alb %>% filter(chromosome == 'NC_053488.1')
dxy.ang.neo.z <- dxy.ang.neo %>% filter(chromosome == 'NC_053488.1')
dxy.ang.jav.z <- dxy.ang.jav %>% filter(chromosome == 'NC_053488.1')
dxy.ang.dim.z <- dxy.ang.dim %>% filter(chromosome == 'NC_053488.1')
dxy.ang.atr.z <- dxy.ang.atr %>% filter(chromosome == 'NC_053488.1')
dxy.nig.smi.z <- dxy.nig.smi %>% filter(chromosome == 'NC_053488.1')
dxy.nig.alb.z <- dxy.nig.alb %>% filter(chromosome == 'NC_053488.1')
dxy.nig.neo.z <- dxy.nig.neo %>% filter(chromosome == 'NC_053488.1')
dxy.nig.jav.z <- dxy.nig.jav %>% filter(chromosome == 'NC_053488.1')
dxy.nig.dim.z <- dxy.nig.dim %>% filter(chromosome == 'NC_053488.1')
dxy.nig.atr.z <- dxy.nig.atr %>% filter(chromosome == 'NC_053488.1')
dxy.smi.alb.z <- dxy.smi.alb %>% filter(chromosome == 'NC_053488.1')
dxy.smi.neo.z <- dxy.smi.neo %>% filter(chromosome == 'NC_053488.1')
dxy.smi.jav.z <- dxy.smi.jav %>% filter(chromosome == 'NC_053488.1')
dxy.smi.dim.z <- dxy.smi.dim %>% filter(chromosome == 'NC_053488.1')
dxy.smi.atr.z <- dxy.smi.atr %>% filter(chromosome == 'NC_053488.1')
dxy.alb.neo.z <- dxy.alb.neo %>% filter(chromosome == 'NC_053488.1')
dxy.alb.jav.z <- dxy.alb.jav %>% filter(chromosome == 'NC_053488.1')
dxy.alb.dim.z <- dxy.alb.dim %>% filter(chromosome == 'NC_053488.1')
dxy.alb.atr.z <- dxy.alb.atr %>% filter(chromosome == 'NC_053488.1')
dxy.neo.jav.z <- dxy.neo.jav %>% filter(chromosome == 'NC_053488.1')
dxy.neo.dim.z <- dxy.neo.dim %>% filter(chromosome == 'NC_053488.1')
dxy.neo.atr.z <- dxy.neo.atr %>% filter(chromosome == 'NC_053488.1')
dxy.jav.dim.z <- dxy.jav.dim %>% filter(chromosome == 'NC_053488.1')
dxy.jav.atr.z <- dxy.jav.atr %>% filter(chromosome == 'NC_053488.1')
dxy.dim.atr.z <- dxy.dim.atr %>% filter(chromosome == 'NC_053488.1')

### Organize mean Fst----

fsts <- c()
fsts <- append(fsts,mean(fst.ery.gut$avg_wc_fst))
fsts <- append(fsts,mean(fst.ery.rus$avg_wc_fst))
fsts <- append(fsts,mean(fst.ery.sav$avg_wc_fst))
fsts <- append(fsts,mean(fst.ery.tra$avg_wc_fst))
fsts <- append(fsts,mean(fst.ery.tyt$avg_wc_fst))
fsts <- append(fsts,mean(fst.gut.rus$avg_wc_fst))
fsts <- append(fsts,mean(fst.gut.sav$avg_wc_fst))
fsts <- append(fsts,mean(fst.gut.tra$avg_wc_fst))
fsts <- append(fsts,mean(fst.gut.tyt$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.sav$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.tra$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.tyt$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.tra$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.tyt$avg_wc_fst))
fsts <- append(fsts,mean(fst.tra.tyt$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.aet$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.ang$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.nig$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.smi$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.alb$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.dim$avg_wc_fst))
fsts <- append(fsts,mean(fst.sav.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.aet$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.ang$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.nig$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.smi$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.alb$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.dim$avg_wc_fst))
fsts <- append(fsts,mean(fst.rus.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.aet$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.ang$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.nig$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.smi$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.alb$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.dim$avg_wc_fst))
fsts <- append(fsts,mean(fst.tyt.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.ang$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.nig$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.smi$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.alb$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.dim$avg_wc_fst))
fsts <- append(fsts,mean(fst.aet.atr$avg_wc_fst))
#fsts <- append(fsts,mean(fst.ang.nig$avg_wc_fst))
fsts <- append(fsts,mean(fst.ang.smi$avg_wc_fst))
#fsts <- append(fsts,mean(fst.ang.alb$avg_wc_fst))
fsts <- append(fsts,mean(fst.ang.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.ang.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.ang.dim$avg_wc_fst))
#fsts <- append(fsts,mean(fst.ang.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.nig.smi$avg_wc_fst))
#fsts <- append(fsts,mean(fst.nig.alb$avg_wc_fst))
fsts <- append(fsts,mean(fst.nig.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.nig.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.nig.dim$avg_wc_fst))
#fsts <- append(fsts,mean(fst.nig.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.smi.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.smi.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.smi.dim$avg_wc_fst))
fsts <- append(fsts,mean(fst.smi.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.alb.neo$avg_wc_fst))
fsts <- append(fsts,mean(fst.alb.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.alb.dim$avg_wc_fst))
#fsts <- append(fsts,mean(fst.alb.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.neo.jav$avg_wc_fst))
fsts <- append(fsts,mean(fst.neo.dim$avg_wc_fst))
fsts <- append(fsts,mean(fst.neo.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.jav.dim$avg_wc_fst))
fsts <- append(fsts,mean(fst.jav.atr$avg_wc_fst))
fsts <- append(fsts,mean(fst.dim.atr$avg_wc_fst))

fsts.a <- c()
fsts.a <- append(fsts.a,mean(fst.ery.gut.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ery.rus.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ery.sav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ery.tra.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ery.tyt.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.gut.rus.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.gut.sav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.gut.tra.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.gut.tyt.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.sav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.tra.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.tyt.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.tra.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.tyt.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tra.tyt.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.aet.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.ang.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.nig.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.smi.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.alb.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.dim.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.sav.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.aet.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.ang.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.nig.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.smi.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.alb.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.dim.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.rus.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.aet.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.ang.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.nig.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.smi.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.alb.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.dim.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.tyt.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.ang.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.nig.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.smi.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.alb.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.dim.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.aet.atr.a$avg_wc_fst))
#fsts.a <- append(fsts.a,mean(fst.ang.nig.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ang.smi.a$avg_wc_fst))
#fsts.a <- append(fsts.a,mean(fst.ang.alb.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ang.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ang.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.ang.dim.a$avg_wc_fst))
#fsts.a <- append(fsts.a,mean(fst.ang.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.nig.smi.a$avg_wc_fst))
#fsts.a <- append(fsts.a,mean(fst.nig.alb.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.nig.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.nig.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.nig.dim.a$avg_wc_fst))
#fsts.a <- append(fsts.a,mean(fst.nig.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.smi.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.smi.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.smi.dim.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.smi.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.alb.neo.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.alb.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.alb.dim.a$avg_wc_fst))
#fsts.a <- append(fsts.a,mean(fst.alb.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.neo.jav.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.neo.dim.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.neo.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.jav.dim.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.jav.atr.a$avg_wc_fst))
fsts.a <- append(fsts.a,mean(fst.dim.atr.a$avg_wc_fst))

fsts.z <- c()
fsts.z <- append(fsts.z,mean(fst.ery.gut.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ery.rus.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ery.sav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ery.tra.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ery.tyt.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.gut.rus.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.gut.sav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.gut.tra.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.gut.tyt.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.sav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.tra.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.tyt.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.tra.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.tyt.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tra.tyt.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.aet.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.ang.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.nig.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.smi.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.alb.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.dim.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.sav.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.aet.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.ang.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.nig.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.smi.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.alb.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.dim.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.rus.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.aet.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.ang.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.nig.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.smi.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.alb.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.dim.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.tyt.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.ang.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.nig.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.smi.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.alb.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.dim.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.aet.atr.z$avg_wc_fst))
#fsts.z <- append(fsts.z,mean(fst.ang.nig.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ang.smi.z$avg_wc_fst))
#fsts.z <- append(fsts.z,mean(fst.ang.alb.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ang.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ang.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.ang.dim.z$avg_wc_fst))
#fsts.z <- append(fsts.z,mean(fst.ang.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.nig.smi.z$avg_wc_fst))
#fsts.z <- append(fsts.z,mean(fst.nig.alb.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.nig.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.nig.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.nig.dim.z$avg_wc_fst))
#fsts.z <- append(fsts.z,mean(fst.nig.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.smi.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.smi.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.smi.dim.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.smi.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.alb.neo.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.alb.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.alb.dim.z$avg_wc_fst))
#fsts.z <- append(fsts.z,mean(fst.alb.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.neo.jav.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.neo.dim.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.neo.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.jav.dim.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.jav.atr.z$avg_wc_fst))
fsts.z <- append(fsts.z,mean(fst.dim.atr.z$avg_wc_fst))

## Note: pairwise Fst between n = 1 species omitted

### Organize mean dxy----

dxys <- c()
dxys <- append(dxys,mean(dxy.ery.gut$avg_dxy))
dxys <- append(dxys,mean(dxy.ery.rus$avg_dxy))
dxys <- append(dxys,mean(dxy.ery.sav$avg_dxy))
dxys <- append(dxys,mean(dxy.ery.tra$avg_dxy))
dxys <- append(dxys,mean(dxy.ery.tyt$avg_dxy))
dxys <- append(dxys,mean(dxy.gut.rus$avg_dxy))
dxys <- append(dxys,mean(dxy.gut.sav$avg_dxy))
dxys <- append(dxys,mean(dxy.gut.tra$avg_dxy))
dxys <- append(dxys,mean(dxy.gut.tyt$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.sav$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.tra$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.tyt$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.tra$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.tyt$avg_dxy))
dxys <- append(dxys,mean(dxy.tra.tyt$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.aet$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.ang$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.nig$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.smi$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.alb$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.dim$avg_dxy))
dxys <- append(dxys,mean(dxy.sav.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.aet$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.ang$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.nig$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.smi$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.alb$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.dim$avg_dxy))
dxys <- append(dxys,mean(dxy.rus.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.aet$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.ang$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.nig$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.smi$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.alb$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.dim$avg_dxy))
dxys <- append(dxys,mean(dxy.tyt.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.ang$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.nig$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.smi$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.alb$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.dim$avg_dxy))
dxys <- append(dxys,mean(dxy.aet.atr$avg_dxy))
#dxys <- append(dxys,mean(dxy.ang.nig$avg_dxy))
dxys <- append(dxys,mean(dxy.ang.smi$avg_dxy))
#dxys <- append(dxys,mean(dxy.ang.alb$avg_dxy))
dxys <- append(dxys,mean(dxy.ang.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.ang.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.ang.dim$avg_dxy))
#dxys <- append(dxys,mean(dxy.ang.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.nig.smi$avg_dxy))
#dxys <- append(dxys,mean(dxy.nig.alb$avg_dxy))
dxys <- append(dxys,mean(dxy.nig.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.nig.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.nig.dim$avg_dxy))
#dxys <- append(dxys,mean(dxy.nig.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.smi.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.smi.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.smi.dim$avg_dxy))
dxys <- append(dxys,mean(dxy.smi.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.alb.neo$avg_dxy))
dxys <- append(dxys,mean(dxy.alb.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.alb.dim$avg_dxy))
#dxys <- append(dxys,mean(dxy.alb.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.neo.jav$avg_dxy))
dxys <- append(dxys,mean(dxy.neo.dim$avg_dxy))
dxys <- append(dxys,mean(dxy.neo.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.jav.dim$avg_dxy))
dxys <- append(dxys,mean(dxy.jav.atr$avg_dxy))
dxys <- append(dxys,mean(dxy.dim.atr$avg_dxy))

dxys.a <- c()
dxys.a <- append(dxys.a,mean(dxy.ery.gut.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ery.rus.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ery.sav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ery.tra.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ery.tyt.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.gut.rus.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.gut.sav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.gut.tra.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.gut.tyt.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.sav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.tra.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.tyt.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.tra.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.tyt.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tra.tyt.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.aet.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.ang.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.nig.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.smi.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.alb.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.dim.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.sav.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.aet.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.ang.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.nig.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.smi.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.alb.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.dim.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.rus.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.aet.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.ang.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.nig.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.smi.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.alb.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.dim.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.tyt.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.ang.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.nig.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.smi.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.alb.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.dim.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.aet.atr.a$avg_dxy))
#dxys.a <- append(dxys.a,mean(dxy.ang.nig.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ang.smi.a$avg_dxy))
#dxys.a <- append(dxys.a,mean(dxy.ang.alb.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ang.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ang.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.ang.dim.a$avg_dxy))
#dxys.a <- append(dxys.a,mean(dxy.ang.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.nig.smi.a$avg_dxy))
#dxys.a <- append(dxys.a,mean(dxy.nig.alb.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.nig.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.nig.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.nig.dim.a$avg_dxy))
#dxys.a <- append(dxys.a,mean(dxy.nig.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.smi.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.smi.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.smi.dim.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.smi.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.alb.neo.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.alb.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.alb.dim.a$avg_dxy))
#dxys.a <- append(dxys.a,mean(dxy.alb.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.neo.jav.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.neo.dim.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.neo.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.jav.dim.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.jav.atr.a$avg_dxy))
dxys.a <- append(dxys.a,mean(dxy.dim.atr.a$avg_dxy))

dxys.z <- c()
dxys.z <- append(dxys.z,mean(dxy.ery.gut.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ery.rus.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ery.sav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ery.tra.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ery.tyt.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.gut.rus.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.gut.sav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.gut.tra.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.gut.tyt.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.sav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.tra.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.tyt.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.tra.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.tyt.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tra.tyt.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.aet.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.ang.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.nig.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.smi.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.alb.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.dim.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.sav.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.aet.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.ang.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.nig.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.smi.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.alb.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.dim.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.rus.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.aet.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.ang.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.nig.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.smi.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.alb.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.dim.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.tyt.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.ang.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.nig.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.smi.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.alb.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.dim.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.aet.atr.z$avg_dxy))
#dxys.z <- append(dxys.z,mean(dxy.ang.nig.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ang.smi.z$avg_dxy))
#dxys.z <- append(dxys.z,mean(dxy.ang.alb.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ang.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ang.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.ang.dim.z$avg_dxy))
#dxys.z <- append(dxys.z,mean(dxy.ang.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.nig.smi.z$avg_dxy))
#dxys.z <- append(dxys.z,mean(dxy.nig.alb.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.nig.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.nig.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.nig.dim.z$avg_dxy))
#dxys.z <- append(dxys.z,mean(dxy.nig.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.smi.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.smi.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.smi.dim.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.smi.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.alb.neo.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.alb.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.alb.dim.z$avg_dxy))
#dxys.z <- append(dxys.z,mean(dxy.alb.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.neo.jav.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.neo.dim.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.neo.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.jav.dim.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.jav.atr.z$avg_dxy))
dxys.z <- append(dxys.z,mean(dxy.dim.atr.z$avg_dxy))

## Note: pairwise dxy between n = 1 species omitted

### Write mean Fst and dxy for table formatting and read in formatted table----

for(i in fsts){print(i)}
for(i in fsts.a){print(i)}
for(i in fsts.z){print(i)}
for(i in dxys){print(i)}
for(i in dxys.a){print(i)}
for(i in dxys.z){print(i)}

comp <- read.table('./mean_Fst_dxy.txt',header=T)
fstrank <- comp %>% arrange(fst)
dxyrank <- comp %>% arrange(dxy)

### Plot ranked mean Fst and dxy----

par(mfrow=c(2,2))
palette(c('royalblue3','goldenrod3','grey'))
plot(fstrank$fst,col=fstrank$category,pch=20,xlab='Mean Fst rank',ylab='Mean Fst',ylim=c(0,0.85))
plot(dxyrank$dxy,col=dxyrank$category,pch=20,xlab='Mean dxy rank',ylab='Mean dxy',ylim=c(0.0045,0.0105))
plot(fstrank$fst.a,fstrank$fst.z,col=fstrank$category,pch=20,xlab='Fst autosome',ylab='Fst Z chromosome',xlim=c(0,1),ylim=c(0,1))
abline(a=0,b=1,lty=2,lwd=1.5)
plot(dxyrank$dxy.a,dxyrank$dxy.z,col=dxyrank$category,pch=20,xlab='dxy autosome',ylab='dxy Z chromosome',xlim=c(0.002,0.011),ylim=c(0.002,0.011))
abline(a=0,b=1,lty=2,lwd=1.5)

## Output at 6.5 x 7.25 (portrait)

## Plot genome-wide dxy vs Fst
par(mfrow=c(1,1))
plot(comp$dxy,comp$fst,col=comp$category,pch=20,xlab='Mean dxy',ylab='Mean Fst')
cor.test(comp$dxy,comp$fst,method='spearman')
